### ISSUE TITLE
Rotated/Flipped Tiles

### ISSUE THREAD

**Issue by RetroCraft** [Seanba/Tiled2Unity#10]
There seems to be a problem with rotated/flipped tiles... When you rotate/flip a tile, in Unity it places weird random transparent lines between tiles. I have no idea what causes them other than the fact that it only happens with flipped or rotated tiles. It's a very, very large XML file, so I doubt you'd be able to examine by hand (about 4.5 MB).

![image](https://cloud.githubusercontent.com/assets/6295913/8121296/f3252e2c-1077-11e5-85ec-818a31d076c9.png)
![image](https://cloud.githubusercontent.com/assets/6295913/8121308/0a591ce8-1078-11e5-9243-4a4a4e270453.png)

**Comment by Seanba** [comment]
Hi James, those are seams that you are seeing and you will see them from time to time on tiles that are not flipped.

Sometimes the texture sampling gets a texel right on the boundary and bleeds into the tile right next to it. The best way to avoid it is to put a 1-pixel width border or margin around each tile that repeats the pixel that comes before it -- if you know what I mean.

**Comment by RetroCraft** [comment]
How might one fix them? I tried using --texel-bias=2048, but it just deformed the tiles.
In Unity:
![image](https://cloud.githubusercontent.com/assets/6295913/8139780/5444b3f6-1124-11e5-9f0e-777c0045fe79.png)
In Tiled:
![image](https://cloud.githubusercontent.com/assets/6295913/8139788/65047d84-1124-11e5-9b68-4f7c6b6a130d.png)

**Comment by Seanba** [comment]
The best fix is to change your source art. You want each tile to have a
margin of 1, and each tile will fill in that margin with the pixel that is
directly above, beside, or below it.

There is a Gimp plugin called Gutter that can help you achieve this. I
don't recommend messing with texel-bias, especially if your texture is
large.

Best,
Sean

**Comment by RetroCraft** [comment]
Source art already has a margin of 1.... It always had for ease of editing and stuff.... Thanks though.

**Comment by Seanba** [comment]
If you send me an example TMX file with the associated textures I can take
a look. You should never get seams when you have padded the boundary of
your tiles with neighboring pixels.

Best,
Sean
