### ISSUE TITLE
Gaps between tiles

### ISSUE THREAD

**Issue by Maxbio1337** [Seanba/Tiled2Unity#104]
I am creating a 2D game. I created a map in Tiled and when I export it to my Unity project via Tiled2Unity I have those weird gaps between the tiles. The gaps do not appear in Tiled. 
It's my first time using Tiled and Tiled2Unity. 

![screenshot_5](https://cloud.githubusercontent.com/assets/29130927/26698542/156cf908-471f-11e7-9d5a-9ee3c30a4ef4.png)

**Comment by Seanba** [comment]
Those are seams. They appear under some conditions, depending on camera location, texture size, texture importer settings, shader, etc..

What are the dimensions of the texture you are using? Can you attach a screenshot of the texture import settings (in Unity) for the texture that is being used here?

**Comment by Maxbio1337** [comment]
I believe this is what you meant?
![screenshot_6](https://cloud.githubusercontent.com/assets/29130927/26699405/6fea9018-4722-11e7-8f10-31863bd5ce0a.png)

**Comment by Seanba** [comment]
Yes, that's it. Change your filter mode from Bilinear to Point. I would expect that to fix it.

**Comment by Maxbio1337** [comment]
It worked! Thank you so much!

**Comment by Seanba** [comment]
Great news. Good luck with your game.
