### ISSUE TITLE
Some tiles appear "slanted" into the editor and game

### ISSUE THREAD

**Issue by Frankloco** [Seanba/Tiled2Unity#106]
**[SOLVED] (Solution and explanation at the bottom of this comment)** Hello everyone,

I have recently noticed this problem with my game and now I can't unsee it anymore and it bothers me quite much. Some of my tiles appear slanted. Here are some properties about my project that I am creating and some screenshots of my problems:

**Texture settings:**
Resolution: 2048x2048
Grid: 16x16
Saved from PS as .PNG no compression (None / Fast) and Interlace (None)

**Tiled:**
Tile x: 16
Tile y: 16

**Tiled2Unity:**
Pixels Per Unit: 32 (using 16, 64, 8 or 128 doesn't change anything except for scaling of the texture)

**Unity:**
![slantedpixtex_01](https://user-images.githubusercontent.com/12886844/26928795-b3f77318-4c57-11e7-8564-1ba43b805e2d.png)
![slantedpixtex_02](https://user-images.githubusercontent.com/12886844/26928796-b5835896-4c57-11e7-8572-7adc2f9b626f.png)

I've tried to set the Texture Type to "Sprite (2D and UI)" as well. Didn't fix it :(.

**Camera Settings:**
![slantedpix_camsettings](https://user-images.githubusercontent.com/12886844/26929092-be3dd596-4c58-11e7-96ba-8a66879121c6.png)

**Editor view**
![slantedpix_01](https://user-images.githubusercontent.com/12886844/26928427-5e2d307c-4c56-11e7-9066-e4a6cf395aeb.png)

![slantedpix_02](https://user-images.githubusercontent.com/12886844/26928438-63e3f438-4c56-11e7-9344-ac8f367a9b46.png)

**In game view**
Even in game it's terrible
![slantedpix_ingame](https://user-images.githubusercontent.com/12886844/26929014-76626782-4c58-11e7-8e8c-a72293840cfd.png)

If anyone would have any clue to fix this. I would be pleased to hear as I would like to continue developing my project without any worries!

_**SOLUTION TO PROBLEM:**_
Create an export commando within Tiled to run the Tiled2Unity exporter that will set the texel-bias to 0.

![2017-06-14](https://user-images.githubusercontent.com/12886844/27130411-7e29122e-5106-11e7-90d0-e7786d118186.png)

Furthermore you should disable "Pixel snap" in the texture it's material within Unity.

Much thanks to Seanba for helping me out with this problem and hopefully other individuals encountering this problem will read this too and see this easy fix!

**Comment by Seanba** [comment]
It is a bit disappointing that getting pixel-perfect visuals in Unity seems like a dark art at times. Do you have anti-aliasing enabled by chance?

**Comment by Frankloco** [comment]
Hello Sean, I did manage to check it today. But anti aliasing was already turned off. Any other ideas?
PS: If I go into 3d mode and fly around it in the scene, the bug still occurs. (screenshot provided)
![2017-06-09](https://user-images.githubusercontent.com/12886844/26972667-0740ca9a-4d13-11e7-8359-f4edbf8fdda7.png)

**Comment by Seanba** [comment]
Hi again. Does the bug occur in the game view outside when you have the scale set to 1.0? I see you have it set to 0.93 in the image above and I wonder if that's because of the way Unity is scaling an image down.

I'm not surprised at visual artifacts appearing in editor mode, btw, but a "real" game view should free of such annoyances.

**Comment by Frankloco** [comment]
Hi Sean,
I am not quite sure as to what you are referring to. As I can not find anything or see something in the images or scene that has a scale of 0.93

**Comment by Seanba** [comment]
Can you export your project as a Unity Project and send it to me? I'm sure I can find some time to take a quick look.

**Comment by Frankloco** [comment]
Sure, any way you can message me your e-mail? I will include the Tiled map and texture used aswell

**Comment by Seanba** [comment]
You can find my email on my website: www.seanba.com

**Comment by anatagawa** [comment]
Any news about this ?

I have the same problem, but also with vertical and horizontal black lines, between each tiles

**Comment by Frankloco** [comment]
@anatagawa If you would have read the first sentence of this thread you would have read that this problem has been solved. You can see the answer/solution to this problem at the bottom of the first comment! ^^

Hopefully it fixes the problem for you aswell!

**Comment by Seanba** [comment]
Frankloco, that's a different problem than what was reported here. What you're seeing is seams. Are there any warnings in your console window (in Unity)?
