### ISSUE TITLE
[Request] Limit, Change or Control the Number of Vertices of a Prefab's Mesh

### ISSUE THREAD

**Issue by InMeVa** [Seanba/Tiled2Unity#107]
Hi Seanba,

As you probably know, the tile dimensions for the grid in Tiled can be chosen freely when a new map is created.
It is my understanding that the chosen tile dimension directly correlates with the number of vertices in the prefab's mesh after conversion via Tiled2Unity. 
Now, you may also know that the max. number of vertices of a prefab in Unity is limited to ~ 65k.
If the Tiled-map one want to export is to large or the tile size was picked to be too small, it can happen that the prefab's mesh is divided into multiple meshes ultimately leading to more draw calls.

I'm aware of the possibility to change the grid size on Tiled and than to re-export, however this breaks the map which eventually means that all the maps have to be created anew. 

Question: 
Is there a way to change, limit or control the number of vertices of the prefab once exported from Tiled via Tiled2Unity?

**Comment by Seanba** [comment]
Hi there. Each tile on a map requires 4 vertices and there is no way around that. The only way to reduce the number of vertices is to reduce the number of layers or size of your map.

Are you experiencing performance issues with draw calls?

**Comment by InMeVa** [comment]
Hi Seanba, 

thank you for your fast response. It makes perfectly sense that each tile needs 4 vertices and I also understand the consequences. Besides your two suggestions on how to reduce the number of vertices, a third option would be setting the tile size in Tiled to a higher format, lets say 64x64 instead of e.g. 8x8 which also does the job. 
Since I have set up a big map with 10+ layers I indeed experience performance issues, especially when using devices with integrated GPUs on higher resolutions (1920x1080). 

One strategy I'm thinking of is to export the Tiled Map Layers as a separate PNG and then assign four vertices to the whole Layer. 
In your opinion, what could be the downside of this approach?

Best,
InMeVa

**Comment by Seanba** [comment]
I think your approach would work fine but do you really need it?

**Comment by InMeVa** [comment]
This is what I want to find out. My favorite solution would include the possibility to choose how many tiles are covered with e.g. four vertices. Instead of saying "each tile has four vertices" I would prefer "Each set of e.g. 2x2 tiles have four vertices". At which point do you assign vertices to tiles?

**Comment by Seanba** [comment]
(I updated my comment above btw)

Covering more tiles with 4 vertices will only work if the tileset texture allows for us. Like, if it were to have neighboring "tiles" burned into the image. It will be a bit tough, IMHO.

When dealing with larger maps I think the answer is always to break them up into smaller parts. It will be more manageable for you as well and should you add more people to your team then it will be easier to break up the work.

**Comment by InMeVa** [comment]
Regarding the size of the map: 
Yes, I comply mostly with the "2-3 screen sized map" -idea with the subsequent combination of the created prefabs. But I also experience performance drops when the rare but larger rooms (or some with more layers) are entered by the Player.
And thank you for your insight on covering more tiles with 4 vertices, I see the problem now. 
It is basically the same problem underlying my attempt to change the tile dimensions after finishing a map. I will have to think about it in more detail and test some assumptions to see what a feasible solution might look like. Thank you very much for this discussion Seanba!

**Comment by InMeVa** [comment]
Update: 
I have now experimented with the import of PNGs without meshes and Tiled2Unity as well as setting the grid-size in Tiled to 64x64 and then export it with Tiled2Unity.  Both approaches work, when it comes down to reduce the number of vertices in Unity. If someone experiences heavy performance issues or has extremely large Tiled-maps which can not be broken down to smaller ones, one should really keep in mind to adjust the grid size before starting to design the level. Also, when it comes down to lighting, the mesh-size may have an influence on the overall feel and performance too, I believe (tests not done yet).
