### ISSUE TITLE
Imported maps not updating on subsequent Imports

### ISSUE THREAD

**Issue by prw56** [Seanba/Tiled2Unity#108]
The initial import into unity (5.6.1f1) works as expected, but after making changes in Tiled and importing again, the prefab in unity does not change. Unity acts as if it notices changes every time I export the map in tiled (displays the Hold on, loading bar), but the prefab does not change appearance or collision at all.

I've noticed this issue before when adding Map properties to change the scale in unity, in that case the changes did not take effect in unity until I made changes to the tiles in the map. Currently though I can not make any changes take effect. There are no warnings or errors during export from tiled or import in Unity.

Edit: restarting Unity causes the changes to take effect. Still believe this is an issue though.

Edit2: Then again, the solution implies this is Unity screwing up rather than Tiled2Unity.

**Comment by Seanba** [comment]
Hi there. Have you made changes to the prefab after it was created by Tiled2Unity? Or changes to the prefab instance in your scene? At times, the link between a game object and its prefab is broken so any further changes you make to the prefab are not reflected in your scene.

**Comment by prw56** [comment]
I don't think so, but even if it was, I tried hitting "revert" on the object and it still did not change. The object was not red (which is the only indicator of a broken link to a prefab that I know of), so I don't think the link was broken.

**Comment by Seanba** [comment]
Can you explain in a little more detail what changes you're making to your map that are not being picked up?

**Comment by prw56** [comment]
Sure, I was trying to paint new tiles. Oddly enough deleting tiles actually worked as expected (as in the import worked in Unity). Before then I only noticed the issue when I was adding in properties to the Map or layers.

**Comment by Seanba** [comment]
Sorry to have replied in so long but I have not been able to reproduce this issue. Is it still happening for you? Do you have any additional details?

**Comment by Seanba** [comment]
I still cannot reproduce so lacking additional information I'm going to close out this issue for now. Feel free to reopen with more details if required. Thanks.
