### ISSUE TITLE
Tiled2Unity Opening tiled file error.

### ISSUE THREAD

**Issue by Stefsteenvoorden** [Seanba/Tiled2Unity#109]
Hi. I have this problem and I don't see any answers online for as far as I could find.
When I try to open a tiled file it says: 
"Loading summary
Succeeded: 0
Warnings: 0
Errors: 1
  Object reference not set to an instance of an object. "
I don't exactly know what this should mean. Any help would be appreciated.

**Comment by Seanba** [comment]
Are you using Windows 8.1 by any chance? I've seen people report errors like this before and it would be nice for me to figure out what is causing this. (So far upgrading to Windows 10 has fixed it but that isn't a great solution.)

**Comment by Stefsteenvoorden** [comment]
No, I'm actually already using Windows 10.

**Comment by Seanba** [comment]
Okay. Can you send me your Tiled map (+ tilesets) then? There must be something special about your map that I'm not accounting for. You can find my email on my blog: www.seanba.com

**Comment by Stefsteenvoorden** [comment]
Hi. I think I just found the problem, but I don't exactly know how to easily solve it. I restarted my PC, and now when I open my Tiled map, A part of the map that uses two different tilesets has red crosses in it. I probably need to re import the tiles, I suppose?

**Comment by Stefsteenvoorden** [comment]
Yay, I solved the problem! When I re-directed the paths of the two tilesets, I needed to save them. I think I'm alright now, But anyway thanks for your help.

**Comment by Seanba** [comment]
Hold on just a second. :)

I'd like the tool to provide good feedback for a user in cases where the TMX file is not well-formed or something. If I understand you properly, the problem was that the TMX file was referencing TSX files that have been moved?

**Comment by Stefsteenvoorden** [comment]
Yeah, I think that was the problem.

**Comment by Seanba** [comment]
I was able to reproduce the problem with a moved/deleted TSX file and the next version of Tiled2Unity will alert the user to the problem with a more helpful message.

**Comment by Seanba** [comment]
Fix published with version 1.0.12.4 of Tiled2Unity. Thanks for the report.

**Comment by bewilderedwanderer** [comment]
I am getting that problem, but I can still export it. The only problem is that my collision are not registering. Do you think that that could be why?

**Comment by bewilderedwanderer** [comment]
I am getting that problem, but I can still export it. The only problem is that my collision are not registering. Do you think that that could be why?
