### ISSUE TITLE
Not able to open Tiled2Unity inside Tiled with command

### ISSUE THREAD

**Issue by lui-habl** [Seanba/Tiled2Unity#110]
Hello! 
When I insert the command `"C:\Program Files\Tiled2Unity\Tiled2Unity.exe" %mapfile` in Tiled it fails to start Tiled2Unity and gives the error: "The command failed to start". 

I am using Tiled version 1.0.1 (64-bit) and Tiled2Unity version 1.0.12.1 (64-bit) on Windows 10 64-bit.

**Comment by Seanba** [comment]
Hi there. Where is Tiled2Unity installed on your PC?

**Comment by lui-habl** [comment]
Hi!  It's installed on the default location `C:\Program Files\Tiled2Unity`

**Comment by Seanba** [comment]
There must be something just a tiny bit off with the command as entered. Can you reply with a screenshot of the error? Thanks.

**Comment by lui-habl** [comment]
Here you go a screenshot from the command configuration and another one from the error. If you need anything else just let me know. I will try to uninstall both and install again in the mean time, just to make sure. 

![command](https://user-images.githubusercontent.com/20427074/27363239-9668e56e-5609-11e7-85a2-f4bc1800ae33.png)
![error](https://user-images.githubusercontent.com/20427074/27363242-9b063f36-5609-11e7-82f6-32654d654b2d.png)

**Comment by Seanba** [comment]
Ah, I see what you did there. :)

You put in the command string where you would put in a name or description for the command.

Maybe this screenshot will help ...
![image](https://user-images.githubusercontent.com/6980630/27365086-c30ba03a-5603-11e7-9476-c3a31b979dcd.png)

**Comment by Seanba** [comment]
BTW, note that in that screenshot above I have Tiled2Unity installed at `Program Files (x86)`. You'll want to keep yours in the `Program Files` directory. (I'm using Win32 in that example where you have the Win64 version installed)

**Comment by lui-habl** [comment]
Oh god, how could I've been so blind! Sorry for raising such a simple issue, and thanks for your help! :)

**Comment by Seanba** [comment]
These things happen. Good luck with your game. :)
