### ISSUE TITLE
Tiled2Unity Lite Causing Unity Editor to Crash

### ISSUE THREAD

**Issue by Mascasc** [Seanba/Tiled2Unity#112]
I'm following along with the Tiled2Unity Lite instructions and everything seems to go off without a hitch on my Linux machine.

However, after the import...I find that my Unity editor consistently gets to the "importing small assets" dialogue on opening and then crashes.

After that, it crashes on every subsequent attempt to open the editor.

Is there any suggested fix for this?

**Comment by Seanba** [comment]
Hi Mascasc, can you send me the exported `*.tiled2unity.xml` file that Tiled2Unity generated for you? I'd like to see if there's something special about it. (You can find my email on www.seanba.com)

**Comment by Mascasc** [comment]
Alright, I sent it.

**Comment by Seanba** [comment]
For the record, Mascasc is experiencing a crash that seems related to his GPU drivers on his Linux box. (It's the same bug [as reported in this thread](https://forum.unity3d.com/threads/cannot-create-game-objects-solution-leads-to-other-problems.392743/#post-2571415).)

No word yet on whether one of the two proposed fixes has solved this specific issues but lurkers may find that information useful.
