### ISSUE TITLE
Components missing in imported maps?

### ISSUE THREAD

**Issue by WintersEnd** [Seanba/Tiled2Unity#114]
Hi,

Recently been watching and following various youtube tutorials on making maps with Tiled and importing with Tiled2Unity and attempted to create a map for my own project.

The issue I have run into is that after watching the tutorials on youtube, I have noticed my imported maps are missing components (notably: `Sorting Layer Exposed (Script)`). 

Youtube tutorial:
![image](https://user-images.githubusercontent.com/22301652/28222862-841ca128-690c-11e7-8e51-42c71d4b4bf7.png)

Mine:
![image](https://user-images.githubusercontent.com/22301652/28222830-69c709e4-690c-11e7-8c81-6bca2c64faaf.png)

I'm not sure if this component is supposed to be available by default and I have tried to manually assign a sorting layer within Tiled by creating a custom property and using `unity:sortingLayerName`. This appears to work with no problem as the imported map shows on the correct sorting layer after importing it - however, the `Sorting Layer Exposed (Script)` component is still missing and I can't seem to find a way to adjust the sorting layer within within Unity itself.

Is this the default behaviour? If so, how do I add/enable the component as the youtube tutorial I have seen has shown?

**Comment by WintersEnd** [comment]
Figured it out - just had to add the runtime script as a component manually. Derp. :(

**Comment by Seanba** [comment]
Hi there. This was actually a bug. You are not expected to add this component manually. This is fixed in version of 1.0.12.3 of Tiled2Unity which I just released moments ago.
