### ISSUE TITLE
My prefab is empty (has nothing on it)

### ISSUE THREAD

**Issue by Gabriel14490** [Seanba/Tiled2Unity#116]
When I click the export button on Tiled2Unity everything goes right and my Prefab is made but the problem is that the Prefab and its components have nothing in them. I have tried reinstalling Tiles2Unity and Unity but it doesen't seem to work. Also whenever i click the empty prefab I get this error message: "SceneView Selected shader is expected to have 7 passes".  It would really help if someone could tell me how to fix it.

**Comment by Gabriel14490** [comment]
Currently running Unity 5.6.2f1 Personal 32bit and Tiled2Unity 1.0.12.3. Also if you don't understand what I mean with empty its that the Prefab is gray with nothing in it.

**Comment by Gabriel14490** [comment]
![image](https://user-images.githubusercontent.com/30281179/28351341-25e7d938-6c1d-11e7-8530-dc8c7c44f307.png)

**Comment by Gabriel14490** [comment]
Now I am getting an error that says: "RenderTexture: Resolving NULL surfaces

**Comment by Seanba** [comment]
Hi Gabriel, those errors sound like issues with your graphics driver. I'd try updating them.

Is your prefab empty when you drag it into your scene? It should have a number of game objects and components on it.

**Comment by Gabriel14490** [comment]
I'll try checking the driver thing because I think it might have something to do, since the computer I am currently using is really old.

**Comment by Gabriel14490** [comment]
Thank you for your help, the computer was the problem. It works perfectly now.
