### ISSUE TITLE
Tiled2Unity doesn't work with Experemental .Net 4.6

### ISSUE THREAD

**Issue by anchpop** [Seanba/Tiled2Unity#120]
I spent a few days trying to debug this myself but got nowhere. All that happens is, when importing, a ___Tiled2Unity_Importer GameObject gets made but never gets removed, and custom import scripts don't run. Not a huge deal of course, just thought it was strange and worth bringing to your attention

**Comment by anchpop** [comment]
By the way, you can turn this on in Edit > Project Settings > Player > Configuration

**Comment by Seanba** [comment]
Thanks for the report. A fix has been found and will be included in the next version of Tiled2Unity.

**Comment by anchpop** [comment]
Thanks! Best dev ever
