### ISSUE TITLE
Bug: incorrect collision mesh generation when importing with .net 4.6

### ISSUE THREAD

**Issue by Gnumaru** [Seanba/Tiled2Unity#124]
The collision mesh is generating correctly when using net35 but not when using net46. Some shapes generate correctly whereas others don't. Maybe this is a clipper bug?

I have not yet made thorough testing for which types of polygons generate incorrect meshes. What I could notice by now is that the incorrect generation seems to appear whenever using non rectangular polygons or rectangular polygons with any side smaller than one world unit. I'm using a tile map with tiles of 8x8 pixels and a pixels per unit value of 8 (1 pixel = 0.125 world unit).

I have attached some images for clarification. The first is importing wit net35:
![captura de tela 53](https://user-images.githubusercontent.com/5783414/29710203-b786169c-8965-11e7-834f-02bbe56af771.png)

And the next is importing with net46:
![captura de tela 54](https://user-images.githubusercontent.com/5783414/29710204-b78cdd88-8965-11e7-9d7a-3ff402d0076c.png)

**Comment by Gnumaru** [comment]
Just after reporting the bug I noticed that the 'Export Scale' property of the 'Tiled Map' component is missing the leading '0.'. This is probably the cause. I didn't change that value, I just exported the tile map within tiled with the following custom command:

"C:\Program Files\Tiled2Unity\Tiled2Unity.exe" -s 0.125 -a %mapfile R:\a\Assets\Tiled2Unity

My windows installation is using a locale (pt-br) where ',' is the decimal separator and '.' is the thousands separator. This is probably the cause.

In my machine, when I do float.Parse("0.1") on RoslynPad (a free .net scratchpad, like LINQPad or the cs-script plugin for notepad++) I get '1' and not '0.1'. But when I do float.Parse("0.1", CultureInfo.InvariantCulture) I get 0.1 as expected.

**Comment by Gnumaru** [comment]
Searching on the github repo for 'float.parse' I got two files

tool/Tiled2Unity/Tiled2UnityLib/TmxClasses/TmxObjectPolyline.cs:45
tool/Tiled2Unity/Tiled2UnityLib/TmxClasses/TmxObjectPolygon.cs:42

Neither use InvariantCulture and both do a string split by ',', which could be the bug's source? But 'tool' is not the source for the unity package, it is for the standalone desktop exporting app. And since the bug shows up only on net46 it must be a bug in the unity scripts, not in the exporting tool.

I noticed that on 'unity/Tiled2Unity/Scripts/Editor/ImportUtils.cs:52' there is a call to 'Convert.ToSingle()'. Like with float.parse, in my machine, Convert.ToSingle("0.1") returns '1' whereas Convert.ToSingle("0.1", CultureInfo.InvariantCulture) returns '0.1'. This is probably the cause...

... Nope, it is not =(. I changed ImportUtils.cs:52 adding the InvariantCulture thing and the Export Scale "did" returned to 0.125, but the collision mesh is still generating incorrectly.

On 'unity/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Prefab.cs:378' there are other calls to Convert.ToSingle, maybe it's them.

**Comment by Gnumaru** [comment]
It was, indeed, an issue with the float parsing logic. on ImportTiled2Unity.Prefab.cs at lines 378, 379, 406 and 407, all the calls to Convert.ToSingle need a System.Globalization.CultureInfo.InvariantCulture parameter to parse the string correctly regardless of the users current locale. Changing those lines fixed the construction of the edgecolliders and polygoncolliders.

**Comment by Gnumaru** [comment]
For convenience, I made a pull request (#125) with the changes mentioned in the last comment.

**Comment by Gnumaru** [comment]
Regarding compatibility, both float.Parse(string, IFormatProvider) and Convert.ToSingle(string, IFormatProvider) do exist on .net 3.5, thus this change should not be a problem for net35 users.

**Comment by Seanba** [comment]
Thanks for finding this and providing a fix. Because of reasons I need to recreate such fixes in my SVN repository and then bring it over to GitHub. I've made these changes now and should have everything updated soon. Thanks again.

**Comment by Seanba** [comment]
Version 1.0.12.4 contains these fixes. Thanks again.
