### ISSUE TITLE
The latest x64 version (1.0.12.4) does not launch

### ISSUE THREAD

**Issue by Gnumaru** [Seanba/Tiled2Unity#128]
The latest x86 version launches successfully but the x64 version does not.

Examining the exe and dlls bundled in the x64 installer, it seems that SkiaSharp.dll and NDesk.Options.dll are x86 assemblies, not x64, maybe that is the problem.

**Comment by Seanba** [comment]
The x86 assemblies should be okay. It looks to me like the Tiled2Unity.exe itself somehow got corrupted. Thanks for letting me know.

**Comment by Seanba** [comment]
Okay. I think I got it right now. Thanks again for letting me know.

**Comment by Gnumaru** [comment]
You are right. The application bundled in the now updated x64 installer launches normally even though SkiaSharp.dll and NDesk.Options.dll still have x86 signatures.

**Comment by Seanba** [comment]
This was fixed with 1.0.12.4
