### ISSUE TITLE
Can't download Tiled2Unity

### ISSUE THREAD

**Issue by Keviloane** [Seanba/Tiled2Unity#131]
Whenever I download Tiled2Unity I can't find it anywhere and when I checked programs and features it seems to say I need to repair it. I have tried every windows file because I am running Windows 8.1.

**Comment by matthuston** [comment]
There's no problem with the Tiled2Unity download.  What browser are you using?  Might try disabling your antivirus, it could be squashing the file?

**Comment by Keviloane** [comment]
Well now I'm on windows 10 and I turned off all my firewalls and defense stuff, but sadly the same problem is occurring, I open the file and it runs the wizard then I agree to everything and the it downloads for like 1 second then stops and says its done downloading.

**Comment by Seanba** [comment]
Hi Keviloane. Maybe some screenshots could help me understand some more what problems you are having? Which file are you opening? Which wizard is running? Why are you downloading *after* you "agree to everything"? I'm a bit confused because I'd expect a download to be the first step to installing Tiled2Unity.

**Comment by Keviloane** [comment]
First I go to the downloads and download the 64bit windows installer,
![image](https://user-images.githubusercontent.com/32231754/30882383-96c10f86-a2bd-11e7-96c6-ad9e97734eb6.png).
Next I click run and it scans the file(I have done this without my windows defender, but the outcome was the same).I click next when the launcher pops up.
![image](https://user-images.githubusercontent.com/32231754/30882474-ece3ad06-a2bd-11e7-99b2-44b10cc705cc.png).
Then I agree to the terms,
![image](https://user-images.githubusercontent.com/32231754/30882511-08adca76-a2be-11e7-9ab2-e7c86a115d88.png).
I click next and install
![image](https://user-images.githubusercontent.com/32231754/30882535-1cd5b810-a2be-11e7-981a-5c6f0bf61707.png)
![image](https://user-images.githubusercontent.com/32231754/30882577-38cf0292-a2be-11e7-844e-29859a899779.png)
It asks if I want this file to make a change to my pc and I agree, then it downloads for 2 seconds and says it is done.
![image](https://user-images.githubusercontent.com/32231754/30882601-5b3fa80e-a2be-11e7-9eaa-e69def052f4b.png)

**Comment by Seanba** [comment]
That last picture is the installer again and because you already have Tiled2Unity installed it doesn't know what you want to do with it (repair or remove).

The executable should be in your `C:\Program Files\Tiled2Unity` folder. Did you look there?

**Comment by Keviloane** [comment]
Thank you very much! I as an idiot need help sometimes, I didn't know the executable was in the folder.

**Comment by Seanba** [comment]
No worries. Good luck with your game.
