### ISSUE TITLE
Make unity:sortingLayerName recursive

### ISSUE THREAD

**Issue by xTiming** [Seanba/Tiled2Unity#132]
Hi there,

It would be very useful to be able to specify the unity:sortingLayerName property in the Map properties instead of the Layer properties and have this cascade downwards and set the sorting layer of all Maps.

As of right now (unless I made a mistake) the unity:sortingLayerName property does nothing in Map properties and all Layers remain at Default sorting layer in Unity.

Thanks!

**Comment by Seanba** [comment]
Hi there. I agree this would be ideal. I've got a heavy workload for the next couple of weeks but I'll try to get to this soon.

**Comment by Seanba** [comment]
Hi again. I just released Tiled2Unity version 1.0.13.0 which will default to the `unity:sortingLayerName` custom property on the map if you don't have it on the layer. Thanks for the suggestion.

**Comment by xTiming** [comment]
Thanks, that's great - I'll certainly be using it!

**Comment by matthuston** [comment]
Thanks here too, this should be useful.
