### ISSUE TITLE
issue importing maps to unity

### ISSUE THREAD

**Issue by arcticanomaly** [Seanba/Tiled2Unity#138]
I'm trying to import my map to unity.

it's supposedly imported successfully, however, nothing shows up in my tiled2unity folder in unity.

> Exporting 'D:\Unity\Projects\An Adventure With Death\Assets\maps\Base Tileset..tmx' to 'D:\Unity\Projects\An Adventure With Death\Assets\Tiled2Unity'
> Compiling tiled2unity file: Base Tileset..tiled2unity.xml
> ImportTexture : will import 'D:\Downloads\roguelike-pack\Spritesheet\roguelikeSheet_transparent.png' to D:\Unity\Projects\An Adventure With Death\Assets\Tiled2Unity\Textures
> InternalTexture : Assets/maps/collision.png
> Exporting to: D:\Unity\Projects\An Adventure With Death\Assets\Tiled2Unity\Imported\Base Tileset..tiled2unity.xml
> Succesfully exported: D:\Unity\Projects\An Adventure With Death\Assets\Tiled2Unity\Imported\Base Tileset..tiled2unity.xml
>   Vertex Scale = 0.0625
>   Object Type Xml = <none>
> --------------------------------------------------------------------------------
> Exporting summary
> Succeeded: 1
>   Succesfully exported: D:\Unity\Projects\An Adventure With Death\Assets\Tiled2Unity\Imported\Base Tileset..tiled2unity.xml
>   Vertex Scale = 0.0625
>   Object Type Xml = <none>
> Warnings: 0
> Errors: 0

i've gone over several posts here with similar isses but the problems don't seem to quite be the same and the solutions havent really done anything.

I get multiples of these two error messages in the console but i'm not sure how related they are to the issue, im still fairly new to unity.

> Assets/Tiled2Unity/Meshes/Base Tileset. is not a valid asset file name. Please make sure there are no slashes or other unallowed characters in the file name. The file will be ignored.
> UnityEditor.AssetDatabase:ImportAsset(String, ImportAssetOptions)
> Tiled2Unity.ImportBehaviour:ImportTiled2UnityAsset(String) (at Assets/Tiled2Unity/Scripts/Runtime/ImportBehaviour.cs:153)
> Tiled2Unity.ImportTiled2Unity:ImportAllMeshes(ImportBehaviour) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Mesh.cs:66)
> Tiled2Unity.ImportTiled2Unity:MaterialImported(String) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Material.cs:37)
> Tiled2Unity.TiledAssetPostProcessor:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs:93)
> UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])

and 

> Ignoring asset refresh of Assets/Tiled2Unity/Meshes/Base Tileset./Base-Tileset._mesh_0002.obj because the folder it is in has not been imported yet!

also, I've been following a game design guide on youtube that uses this to create the maps. as far as i can tell, I've done anything differently to them and I don't have unity or tiled2unity set up any differently but they seemingly had no issues

**Comment by arcticanomaly** [comment]
solved. feel like an idiot.

**Comment by Seanba** [comment]
Hi there. Was this a problem because of the two periods in your Tiled file? i.e. `Base Tileset**..**tmx`?

I can try to detect stuff like that so that others are not tripped up. It seems like an easy mistake to make.

**Comment by arcticanomaly** [comment]
Yeah it was, I'm not sure how it slipped in there. 

It was surprisingly hard to spot
