### ISSUE TITLE
Tiled Layers don't get unity:tag's applied to children

### ISSUE THREAD

**Issue by willt** [Seanba/Tiled2Unity#14]
If you define a unity:tag to a Layer property it doesn't propagate to child objects.
unity:layer gets applied to all children.

I need this so that tag gets applied to the Collision child.

If this is intended behaviour could you let me know if there is a work around available ?
Thanks!

**Comment by Seanba** [comment]
Sorry for the super late replay, but yes, this is intended. As a workaround you can write a custom importer to add tags to the children or (even better, IMO) keep the tags where they are and have your scripts know how to access children from the "root" game object.
