### ISSUE TITLE
Stuck with "Import Wait_Materials" while importing.

### ISSUE THREAD

**Issue by Bugari** [Seanba/Tiled2Unity#143]
I cannot any longer import map to project. It gets stuck, and leaves created file __tiled2unity_importer.

![tiled2unity_issue](https://user-images.githubusercontent.com/2004358/33796342-acbb6eb6-dcf2-11e7-9f4d-fc42fefc34ab.png)

I tired re-importing tiled2unity to project, remaking map, remaking tileset.. nothing helped. I don't recieve any errors or warnings anywhere. 

What can I do to fix this? Thanks for your help.

**Comment by Seanba** [comment]
Hi there. Try deleting all `__tiled2unity_importer` objects in your scene and export again. If you still have problems then post the contents of your Console output window. Tiled2Unity usually gives information on what went wrong there.

**Comment by Bugari** [comment]
I did try that - no success. Unity console is empty. You can see Tiled2Unity console result below.

```
Command: C:/Users/Bugar/Documents/GitHub/SoulBow/Tiled/TestMap.tmx
--------------------------------------------------------------------------------
Arguments summary
Succeeded: 0
Warnings: 0
Errors: 0
--------------------------------------------------------------------------------
Opening C:\Users\Bugar\Documents\GitHub\SoulBow\Tiled\TestMap.tmx ...
Opening C:\Users\Bugar\Documents\GitHub\SoulBow\Tiled\Walls.tsx ...
Map details: { "TestMap" size = 15x10, tile size = 64x64, # tiles = 24 }
Parsed: C:\Users\Bugar\Documents\GitHub\SoulBow\Tiled\TestMap.tmx 
--------------------------------------------------------------------------------
Loading summary
Succeeded: 1
  Parsed: C:\Users\Bugar\Documents\GitHub\SoulBow\Tiled\TestMap.tmx 
Warnings: 0
Errors: 0
--------------------------------------------------------------------------------
Exporting 'C:\Users\Bugar\Documents\GitHub\SoulBow\Tiled\TestMap.tmx' to 'C:\Users\Bugar\Documents\GitHub\SoulBow\Assets\Tiled2Unity'
Compiling tiled2unity file: TestMap.tiled2unity.xml
InternalTexture : Assets/Sprites/Walls.png
Exporting to: C:\Users\Bugar\Documents\GitHub\SoulBow\Assets\Tiled2Unity\Imported\TestMap.tiled2unity.xml
Succesfully exported: C:\Users\Bugar\Documents\GitHub\SoulBow\Assets\Tiled2Unity\Imported\TestMap.tiled2unity.xml
  Vertex Scale = 0.015625
  Object Type Xml = <none>
--------------------------------------------------------------------------------
Exporting summary
Succeeded: 1
  Succesfully exported: C:\Users\Bugar\Documents\GitHub\SoulBow\Assets\Tiled2Unity\Imported\TestMap.tiled2unity.xml
  Vertex Scale = 0.015625
  Object Type Xml = <none>
Warnings: 0
Errors: 0
```

**Comment by Seanba** [comment]
Can you send me your exported `TestMap.tiled2unity.xml` file? You can find my email address on my blog: www.seanba.com

I'll also need that texture you have at `Assets/Sprites/Walls.png`

Thanks.

**Comment by Bugari** [comment]
Email sent :)

**Comment by Seanba** [comment]
Thanks, Bugari. I've found the issue and I've sent you a fix. If that works out for you then I'll roll it out with the next Tiled2Unity version.

**Comment by Seanba** [comment]
Version 1.0.13.2 fixes this. Thanks for the bug report.
