### ISSUE TITLE
Exporting 32x32 tiles as a single unit

### ISSUE THREAD

**Issue by JamesMcMahon** [Seanba/Tiled2Unity#15]
I'm attempting to export a tiled map made up of 32x32 tiles to a Unity so that I get 1 tile == 1 unit. I'm using a vertex scale of `0.032` and am running into some trouble. The scale of the map appears to "drift" and misalign with Unity's scale.

Here is what my tiled map looks like for reference, this is a 16x16 map made up of 32x32 tiles:
![tiledmap](https://cloud.githubusercontent.com/assets/916676/9508328/af6d5cfe-4c22-11e5-9d82-aa691d36c3b4.PNG)

And here is the imported map (some of the mesh renderers on the more colorful layer are turned off):
![unityimport](https://cloud.githubusercontent.com/assets/916676/9508388/eeb1c7d8-4c22-11e5-9e48-b462d2e23a6f.PNG)

If you look closely, the scale of each tile doesn't appear to be consistent. So while it appears to be mostly aligned in the upper left (note the grid lines):
![unityimportupperleft](https://cloud.githubusercontent.com/assets/916676/9508402/0ebf26a6-4c23-11e5-851a-6546297cfad0.PNG)

By the time you get to the upper right, the grid lines no longer match:
![unityimportupperright](https://cloud.githubusercontent.com/assets/916676/9508417/29e6edf6-4c23-11e5-906e-3cb0a0224022.PNG)

I am fairly new to Unity and just started using Tiled2Unity the other day so there is a chance that my vertex scale is just off but it seems like based on [your article](http://www.seanba.com/revisit-tiled2unity-scale.html) the proper scale for 32x32 should be `0.032`. 

Any help is welcome.

**Comment by JamesMcMahon** [comment]
I also looked at the source code to see if I could find the source of the "drift".

```
        public static Vector3D PointFToUnityVector(PointF pt)
        {
            // Unity's coordinate sytem has y-up positive, y-down negative
            // Apply scaling
            PointF scaled = pt;
            scaled.X *= Program.Scale;
            scaled.Y *= Program.Scale;

            // Have to watch for negative zero, ffs
            return new Vector3D(scaled.X, scaled.Y == 0 ? 0 : -scaled.Y, 0.0f);
        }
```

Could the conversion from a `float` to a `double` here be responsible? When `0.032f` is converted to a `double` it would result in `0.0320000015199184` (see http://csharppad.com/gist/5cf382820ae0d538233d). That is such a minor difference that I am not sure if it would have an affect, but it was one thing that stood out at me after briefly looking at the source.

**Comment by Seanba** [comment]
Hi James, I'm away from my desk but shouldn't the scale factor be 1/32 instead of 32/100?

1/32 == 0.3125, a very nice number to represent in floating point.

Best,
Sean

**Comment by JamesMcMahon** [comment]
Ah, yup that is totally it. I thought translating `0.01` to `0.032` made sense because I was unsure of how you arrived at `0.01` in the first place. But 1/32 gives me a value of `0.03125`, which scales quite nicely.

Thanks so much for you help, I had obviously been staring at this too long today as you can tell by me poking around the code. :smile: 

At the very least this issue will hopefully allow people to Google the correct Tiled2Unity vertex scale for a 32x32 tile.

**Comment by TitoOliveira** [comment]
Hi guys, i was searching for a similar issue and google led me here.
Have you managed to solve your problems? I have a 16px tileset and seems like it is not possible to have float values with more than two decimals places on Tiled. How did you manage to scale your map by 0.03125 when importing it to unity?

**Comment by JamesMcMahon** [comment]
So it's been a long time since I looked at any of this stuff but I believe it should be 1/16 or `0.0625` for a 16px tileset.

**Comment by TitoOliveira** [comment]
Yeah. My issue is that when setting a custom property in tiled, i either have to live with 0.06, or 0.07. Wanted to know if you guys managed to circumvent this limitation.

**Comment by JamesMcMahon** [comment]
Oh I don't know. I don't remember there be a decimal place limitation. Maybe that was something that was introduced in the year since this issue was created.

Might be worth starting a new issue if you are running into trouble.

**Comment by Seanba** [comment]
If you guys are entering this value into Tiled2Unity then take note that I've changed Vertex Scale to "Pixels Per Unit". This way you enter the same value as you do in Unity for your Sprites.

![image](https://cloud.githubusercontent.com/assets/6980630/17793416/c873e772-656c-11e6-8280-bce50a5a042b.png)

**Comment by TitoOliveira** [comment]
Thanks for the reply. I'll check this soon
