### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by maxwellnewage** [Seanba/Tiled2Unity#16]
I did replaced the code of method OnPostprocessModel in Scripts/Editor/TiledAssetPostProcessor.cs at download version of your website, because I could not export...there are the errors:

Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(107,65): error CS0234: The type or namespace name `ReflectionProbeUsage' does not exist in the namespace `UnityEngine.Rendering'. Are you missing an assembly reference?
Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(107,20): error CS1061: Type `UnityEngine.MeshRenderer' does not contain a definition for `reflectionProbeUsage' and no extension method `reflectionProbeUsage' of type `UnityEngine.MeshRenderer' could be found (are you missing a using directive or an assembly reference?)

**Comment by Seanba** [comment]
Hi Maximiliano, what version of Unity are you using? I wonder if this is a
problem with Unity 4?

Best,
Sean

**Comment by maxwellnewage** [comment]
I am using unity 4.6.2f1

**Comment by Seanba** [comment]
Okay, I'll put out a proper fix for Unity 4 users sometime this week. In
the meantime comment out this lines in TiledAssetPostProcessor.cs at line
107:

                //mr.reflectionProbeUsage =
UnityEngine.Rendering.ReflectionProbeUsage.Off;

Alternatively, you can upgrade to Unity 5. At this point I'm guessing
reflection probes are a feature new to Unity 5.

Best,
Sean

**Comment by maxwellnewage** [comment]
mm yes, but i don't like Unity 5, because changes the physics about Unity 4, and break my projects :/
