### ISSUE TITLE
Object types not being exported with JSON/JavaScript

### ISSUE THREAD

**Issue by spectre-hydra** [Seanba/Tiled2Unity#163]
![image](https://user-images.githubusercontent.com/33549831/37982959-46fc8ace-31f2-11e8-872c-7b57afd1607f.png)

1. Create a TileSet with some objects.
2. Set a type to each object, ex. TYPE1, TYPE123
3. Create some objects on a TileMap
4. Export as JSON/JS:

![image](https://user-images.githubusercontent.com/33549831/37983033-7c1f6708-31f2-11e8-810a-ae8b9d10b797.png)

Export as LUA (working, visible mappings):

![image](https://user-images.githubusercontent.com/33549831/37983093-ae28bbc8-31f2-11e8-8b26-bc083446c3f1.png)

**Comment by Seanba** [comment]
Hi there. I'm afraid you have the wrong github repository.
