### ISSUE TITLE
Tiled2Unity Cannot Find My Map File

### ISSUE THREAD

**Issue by LampIsMe** [Seanba/Tiled2Unity#169]
Hi, so I made a map with Tiled, and saved it in my desktop as a .tmx file, then I went to my Tiled2Unity, but I can't find any of my .tmx files? In my previous Unity game, I was able to find the tmx file and use it as a map, but in my new game, the tiled2Unity, when I'm trying to import a map, doesn't find any of the .tmx files

**Comment by Seanba** [comment]
Are you saying that the exporter cannot load your TMX file? I'm not sure what you mean by Tiled2Unity not being able to "find" your map. Maybe some screen shots would help?

**Comment by LampIsMe** [comment]
So I go to my library, then to desktop, and none of my TMX files are there,
so I can’t select any file to export to my unity TILED2UNITY folder, but I
clearly see my tmx files on my desktop

**Comment by LampIsMe** [comment]
![picture1](https://user-images.githubusercontent.com/34934612/41016301-5a61972e-6903-11e8-9ccc-8cffd0f70be6.GIF)
![picture2](https://user-images.githubusercontent.com/34934612/41016305-5cf76950-6903-11e8-95d5-11072bc925e1.GIF)
![picture3](https://user-images.githubusercontent.com/34934612/41016306-5fd5fdb2-6903-11e8-96ee-b18d2b56bd50.GIF)

**Comment by LampIsMe** [comment]
As you can see, the test area.tmx (in the middle of the desktop) is in my desktop, but I can't find it when I am trying to export it, what should I do?

**Comment by Seanba** [comment]
Oh, okay. It looks like you are clicking on "Object Types XML..." You want File -> Open Tiled File.
