### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by Brianatorj** [Seanba/Tiled2Unity#172]
On Tiled2Unity I am attempting to get my test map into Unity for, of course, testing. Every time so far has not worked. Here is exactly what it says:

Succeeded: 1
Parsed: C:\Users\brian_000\Documents\ActionRPG\Assets\Maps\test_area.tmx
Warnings: 0
Errors: 1
Tileset file does not exist: C:\Base Tileset.tsx

Can you please tell me how to fix this?
Thank you!

**Comment by Seanba** [comment]
Hi there, Brian. These kind of errors are almost always caused by moving tilesets around but not updating your TMX file to look for the tileset in the new location. Did you double check that  `C:\Base Tileset.tsx` exists?

**Comment by EnterAnUsername** [comment]
I have the same problem and the file doesn't exist but when I go for svae the tileset here the file exist. I've posted an issue with some script if you wanna take a look

**Comment by Brianatorj** [comment]
Seanba, due to certain restrictions on my computer I can't move the Base Tileset to the C: part of the computer. Any way I can change the location that Tiled2Unity looks for the Tileset?

**Comment by Seanba** [comment]
Where does Tiled look for that tileset? Tiled2Unity will look for it in the same location.

You can always edit raw TMX file to look for a tileset (or some other dependency) in another location.

**Comment by Brianatorj** [comment]
I have no idea where TIled looks for the Tileset nor how to make it look somewhere for the tileset. I also do not know how to edit raw TMX files to look for the tileset (I am new to programming and stuff)

**Comment by Seanba** [comment]
When you open your TMX file in Tiled and Tiled cannot find a tileset our texture or some other dependency then it should pop up a dialog asking you to locate that file in another location. Have you tried that?

**Comment by Brianatorj** [comment]
No I am going to try that now

**Comment by Brianatorj** [comment]
It is working just fine, no pop-ups or anything.

**Comment by Seanba** [comment]
Do you know if that tileset is actually being used by your map anymore? It's possible you have an old reference in your TMX file that should now be removed.

**Comment by Brianatorj** [comment]
I just deleted and remade the Testing Map, and deleted and then remade the Tileset, but now the export button isn't working. I went to check and seen that this tileset IS where it is supposed to be (C:/Base Tileset).

**Comment by Seanba** [comment]
Hi again. Can you elaborate a bit more on "export button isn't working"? Are you seeing any errors or warnings?

FWIW, I'm working on a new version of Tiled2Unity that will greatly simplify the export process (as in, there isn't one, everything is done in Unity) and you may be better off waiting on that if this is giving you so much trouble.

**Comment by Brianatorj** [comment]
By not working I mean the export button won't be pressed again, like it should after exporting, even though i did not exporting.

**Comment by Seanba** [comment]
If you can't click on the export button then make sure your "Export To ..." directory is set up to correctly. (In other words, it has be a valid Unity project.)

If you're still stuck send a screenshot perhaps?

**Comment by Brianatorj** [comment]
![screenshot 24](https://user-images.githubusercontent.com/40583200/42604938-1142d8c6-852a-11e8-9ebd-e821a40eedb6.png)

**Comment by Seanba** [comment]
That's a Tiled error, not Tiled2Unity. It looks like you're trying to "export" a tileset file but I don't think you want to be doing that.

It think things have perhaps approached a degree of complexity that it would be best to start off again small. Try with a simple, small map, with your TMX file, tilesets, and textures all in one directory that you have access to. From that see if you can use the Tiled2Unity exporter successfully to get your map into your Unity project.

**Comment by Brianatorj** [comment]
I just tried that and it is saying the same thing as earlier. I also can't seem to figure out how to properly change the pathway Tiled2Unity is taking. If I can figure out how to do that than I believe I will be able to fix the problem.

**Comment by Seanba** [comment]
Hi again:
> I just tried that and it is saying the same thing as earlier.

Please help me out by being a bit more specific. What is "it"? (Tiled or Tiled2Unity?) and what is "same thing as eariler?" (An error about a missing tileset or the "unknown file format" error?)

**Comment by Brianatorj** [comment]
Tiled2Unity is saying that they can't find C:\Base Tileset. I also tried changing the Tileset's name hoping it would fix it, but it didn't work.

**Comment by Seanba** [comment]
Can you send me your TMX file? You can find my email address on my website: www.seanba.com

**Comment by Brianatorj** [comment]
I did it! I figured it out!

**Comment by Brianatorj** [comment]
I opened my Tiled file in Unity, and then Tiled said it couldn't locate the Tileset. It then gave me an option to locate the Tileset so I used that to use the Tileset I had recently saved. I then saved the Map and then used Tiled2Unity to access the Map one more time. Then it worked just fine!

**Comment by Seanba** [comment]
Okay. Glad you got it working.
