### ISSUE TITLE
Tileset file does not exist

### ISSUE THREAD

**Issue by EnterAnUsername** [Seanba/Tiled2Unity#173]
Okay I know this issue has been asked a few times but I've tried to fix it without succes. 

![image](https://user-images.githubusercontent.com/36824875/42313516-423b46ca-8043-11e8-81ad-81a699e15621.png)

This is what Tiled2Unity tell me. Indeed this is true, in the Tiled file I don't have any "Tileset.tsx".

![image](https://user-images.githubusercontent.com/36824875/42313646-873e49a2-8043-11e8-9c5c-d9e44858428a.png)

So I decided to save my tileset in the Tiled file.

![image](https://user-images.githubusercontent.com/36824875/42313726-b3029e8a-8043-11e8-8e0e-7da246b6525e.png)

![image](https://user-images.githubusercontent.com/36824875/42313767-cf1384e0-8043-11e8-9f01-755850b72e3a.png)

But here the file exist, I don't know why...

So, I'd like to know how to fix this. How to have my tileset detected by Tiled2Unity.
The Tiled2Unity Package is in Unity. So I don't think that comes from here.

**Comment by Seanba** [comment]
Hi there. I don't know what's going on here but Tiled2Unity won't be able to find a file if you can't find it yourself in Windows Explorer. Why Tiled *does* seem to see the file is a mystery to me.

I would move the Tileset file so that it is not in your `Program Files (x86)` directory anyway as the Windows OS will sometimes limit read/write access to files that live there. Try moving it somewhere more under your control and fix up your map to reference the Tileset at its new location and see if that fixes you up.

**Comment by EnterAnUsername** [comment]
Okay so now I've my Tileset on my Desktop, the tileset exist.

![image](https://user-images.githubusercontent.com/36824875/42411379-37def05a-81fb-11e8-8c6b-91bdede637db.png)

But T2U want the file in a precise location which is C:\Program Files (x86)\Tiled\Tileset.tsx
How do I change that ?

**Comment by Seanba** [comment]
Try opening your map in Tiled. It should give you the opportunity to find your find the tileset file you moved. (That won't work if you have that tileset file in both locations though.)

**Comment by EnterAnUsername** [comment]
Okay, it's done. I found how to fix it thanks to you !

For those who can't fix it. Here what to do. 
Just create a folder in a good location like desktop. Whatever the name. And put your original Tileset in it. So go to tiled. Create a new map and tileset. Do whatever you want to do. And save your tileset AND your map in the folder you've created. And finally go to T2U, it'll find all you folder. 
In this case it's just a location problem. DO NOT MOVE YOUR FILES. If you create a map the location where is your tileset is definitve and if you move your original tileset and the .tsx file, Tiled2Unity will don't find'em. 

Thanks you Seanba.
