### ISSUE TITLE
Object reference not set as an instance while parsing layer data as Xml elements.

### ISSUE THREAD

**Issue by brantkings** [Seanba/Tiled2Unity#174]
Hey, I just downloaded the latest Tiled and it broke Tiled2Unity for me :/

I'm receiving this error:

Command: -s 0.0625 C:\Projects\LongHatHouse\dandara\dandaraDlc\DandaraUnity\Assets\Jumper\TiledFiles\Maps\Area5\A5_Test.tmx C:\Projects\LongHatHouse\dandara\dandaraDlc\DandaraUnity\Assets\Tiled2Unity
--------------------------------------------------------------------------------
Arguments summary
Succeeded: 0
Warnings: 0
Errors: 0
--------------------------------------------------------------------------------
Opening C:\Projects\LongHatHouse\dandara\dandaraDlc\DandaraUnity\Assets\Jumper\TiledFiles\Maps\Area5\A5_Test.tmx ...
Parsing map root ...
Parsing tileset elements ...
Opening C:\Projects\LongHatHouse\dandara\dandaraDlc\DandaraUnity\Assets\Jumper\TiledFiles\Tilesets\ExternalTilesets\Dreamlands.tsx ...
Parse internal tileset 'Dreamlands' (gid = 1) ...
Added 1024 tiles
Parse tile data (gid = 1, id 0) ...
Parse tile data (gid = 2, id 1) ...
Parse tile data (gid = 3, id 2) ...
Parse tile data (gid = 4, id 3) ...
Parse tile data (gid = 5, id 4) ...
Parse tile data (gid = 12, id 11) ...
Parse tile data (gid = 13, id 12) ...
Parse tile data (gid = 33, id 32) ...
Parse tile data (gid = 34, id 33) ...
Parse tile data (gid = 35, id 34) ...
Parse tile data (gid = 36, id 35) ...
Parse tile data (gid = 37, id 36) ...
Parse tile data (gid = 65, id 64) ...
Parse tile data (gid = 66, id 65) ...
Parse tile data (gid = 67, id 66) ...
Parse tile data (gid = 68, id 67) ...
Parse tile data (gid = 69, id 68) ...
Parse tile data (gid = 97, id 96) ...
Parse tile data (gid = 98, id 97) ...
Parse tile data (gid = 99, id 98) ...
Parse tile data (gid = 100, id 99) ...
Parse tile data (gid = 101, id 100) ...
Parse tile data (gid = 107, id 106) ...
Parse tile data (gid = 111, id 110) ...
Parse tile data (gid = 129, id 128) ...
Parse tile data (gid = 130, id 129) ...
Parse tile data (gid = 131, id 130) ...
Parse tile data (gid = 132, id 131) ...
Parse tile data (gid = 133, id 132) ...
Parse tile data (gid = 139, id 138) ...
Parse tile data (gid = 143, id 142) ...
Parse tile data (gid = 161, id 160) ...
Parse tile data (gid = 162, id 161) ...
Parse tile data (gid = 163, id 162) ...
Parse tile data (gid = 164, id 163) ...
Parse tile data (gid = 165, id 164) ...
Parse tile data (gid = 171, id 170) ...
Parse tile data (gid = 175, id 174) ...
Parse tile data (gid = 193, id 192) ...
Parse tile data (gid = 194, id 193) ...
Parse tile data (gid = 195, id 194) ...
Parse tile data (gid = 196, id 195) ...
Parse tile data (gid = 197, id 196) ...
Parse tile data (gid = 203, id 202) ...
Parse tile data (gid = 207, id 206) ...
Parse tile data (gid = 225, id 224) ...
Parse tile data (gid = 226, id 225) ...
Parse tile data (gid = 227, id 226) ...
Parse tile data (gid = 228, id 227) ...
Parse tile data (gid = 229, id 228) ...
Parse tile data (gid = 235, id 234) ...
Parse tile data (gid = 239, id 238) ...
Parse tile data (gid = 257, id 256) ...
Parse tile data (gid = 258, id 257) ...
Parse tile data (gid = 259, id 258) ...
Parse tile data (gid = 260, id 259) ...
Parse tile data (gid = 261, id 260) ...
Parse tile data (gid = 298, id 297) ...
Parse tile data (gid = 299, id 298) ...
Parse tile data (gid = 300, id 299) ...
Parse tile data (gid = 330, id 329) ...
Parse tile data (gid = 331, id 330) ...
Parse tile data (gid = 332, id 331) ...
Parse tile data (gid = 362, id 361) ...
Parse tile data (gid = 363, id 362) ...
Parse tile data (gid = 364, id 363) ...
Parse tile data (gid = 394, id 393) ...
Parse tile data (gid = 395, id 394) ...
Parse tile data (gid = 396, id 395) ...
Parsing layer elements ...
Parse properites ...
Parse Plain Color layer data ...
Parsing layer data as Xml elements ...
Object reference not set to an instance of an object.
--------------------------------------------------------------------------------
Loading summary
Succeeded: 0
Warnings: 0
Errors: 1
  Object reference not set to an instance of an object.
--------------------------------------------------------------------------------

Might have to do with [this issue](https://github.com/Seanba/Tiled2Unity/issues/149) too? As the maps simply aren't working.

Thanks!

**Comment by Seanba** [comment]
From the output it looks like you have an old version of Tiled2Unity. Do you know what you are using? IIRC, this was a problem with blank tiles when using XML as your `Tile Layer Format` but it should be fixed now.

**Comment by brantkings** [comment]
![image](https://user-images.githubusercontent.com/2578035/42971575-3a21b5f0-8b83-11e8-8f3e-14ce29b07b03.png)

Oh I see, it's because I just updated the Unity thing through the Help part in Tiled2Unity! I thought that was enough for some reason.

It works, thanks for such a fast reply! :)

**Comment by Seanba** [comment]
Thanks for letting me know you got it working. :)
