### ISSUE TITLE
"The object you are trying to replace does not exist or is not a Prefab."

### ISSUE THREAD

**Issue by Avalin** [Seanba/Tiled2Unity#182]
I get this error when I use Tiled2Unity it in Unity version 2018.3.0b1

The object you are trying to replace does not exist or is not a Prefab.
UnityEditor.PrefabUtility:ReplacePrefab(GameObject, Object, ReplacePrefabOptions)
Tiled2Unity.ImportTiled2Unity:CreatePrefab(XElement, ImportBehaviour) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Prefab.cs:97)
Tiled2Unity.ImportTiled2Unity:ImportAllPrefabs(ImportBehaviour) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Prefab.cs:47)
Tiled2Unity.ImportTiled2Unity:MeshImported(String) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Mesh.cs:39)
Tiled2Unity.TiledAssetPostProcessor:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs:98)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])﻿

Edit: My solution for now has been to downgrade. It works fine as of 2018.2.11f1 :)

**Comment by Seanba** [comment]
Hi Avalin, I would guess the was an earlier error with importing your map file that is stopping the new prefab from being created. If you send me your project as a Unity Package I can try to debug.

BTW, you may have better luck with [SuperTiled2Unity](https://seanba.com/supertiled2unity.html) - the new way of getting Tiled assets in Unity. Thanks.

**Comment by Simnaan** [comment]
I'm getting the same problem on Unity18.3.8f1 and I can't find a solution to this problem please help!!!

**Comment by seanb-22ct** [comment]
I'm not sure Tiled2Unity will still work with Unity 18.3.8f1. What issues are you having with SuperTiled2Unity?

**Comment by Simnaan** [comment]
I import all the files for the map and then it just loops back and tells me to add the files I just added in again

**Comment by seanb-22ct** [comment]
Hi again, @Simnaan. Are the relative paths for your TMX, TSX, and texture files still intact? I would guess the problem is that you copied the files into your Unity project, perhaps into the same folder, and that broke the relative paths?

You can send me your project (sean@seanba.com) and I can check that for you.

**Comment by seanb-22ct** [comment]
If you check the error that is being reporting it is telling you where it expects the files referenced by your TMX to exist. My bet is that you have them in the wrong location. 

Try opening your imported TMX in Tiled. You should be getting similar errors there. Tiled will also give you the chance to "find" the files again (which changes the relative path). This is probably your fatest/best way to fix.
