### ISSUE TITLE
Create specified Tiled layer with quads instead single mesh.

### ISSUE THREAD

**Issue by AndyGFX** [Seanba/Tiled2Unity#19]
Hi,

I'm happy with Tiled2Unity asset but I found that I need create a few layers with seperated quad mesh only. I thing, this feature is usefull for all and from this point of view, should be nice to have any option or layer properties to generate defined layer with mesh per tile, instead single layer mesh. 

AndyGFX

**Comment by Seanba** [comment]
Hi Andy, you can use Tile Objects on an Object Layer. These objects are exported as separate quads.
