### ISSUE TITLE
Question: Tips for specifying collision region for many many tile types?

### ISSUE THREAD

**Issue by abelnation** [Seanba/Tiled2Unity#20]
With some tile art, there may be tons of tiles that all have a simple square (100% filled) collision area.  Do you have tips, ideas for rapidly applying the collision area to all those tiles at once? Same goes for simple ramps, etc.

One thought was using Tiled's auto-mapping feature, and using a separate collision layer, but tiled2unity seems geared towards mapping the layer and collision areas into the same mesh in unity.  Thoughts?

**Comment by Seanba** [comment]
Abelnation, that is exactly what I do for some of my projects. I'll have just one tile in it's own tileset with the collision I want on it and use automapping to put all collision tiles into a specific layer.

On that layer I will have a custom property, "unity:ignore" with a value of "visual". That tells Tiled2Unity to only import the collision data and ignore the visual aspects.
