### ISSUE TITLE
Question: Re-mapping tile art once in unity

### ISSUE THREAD

**Issue by abelnation** [Seanba/Tiled2Unity#21]
I was reading the towerfall dev blog post about auto-tiling (http://towerfall.tumblr.com/post/98906957031/detailing-process-i-still-want-to-prototype-a-new).  

I was curious if it's possible to use tiled2unity to create a mesh using some base tiles, which can then be mapped to different tile "themes" in unity.  E.g. You could create 5 "theme" tilesheets, where each type of tile is in the same corresponding place in the tilesheet.  I'm curious if I can swap out the underlying tile texture image once in unity to change the style of the tiles.  

Thoughts?  and Thanks! Love the tool

**Comment by Seanba** [comment]
Hi abelnation, yes, it should be trivial to change the material on a layer with just a bit of scripting. You may want to use a custom Tag on the layers you are interested in. Then you can search for each GameObject by its Tag, get a reference to the MeshRenderer on it, and then set the material on that mesh renderer.
