### ISSUE TITLE
Map and map tilesets not importing into Unity

### ISSUE THREAD

**Issue by gooball60** [Seanba/Tiled2Unity#27]
Alright, so things used to work great, until I got a new computer and re-downloaded newer versions of Tiled, Tiled2Unity, and Unity itself. Now I can seem to get Tiled2Unity to work. The *.tiled2unity.xml file exports just fine, but that's it. Nothing in Unity shows up, the prefabs, materials, nothing. I also get an error in Unity when I export it: 
`Importing 'Assets/Tiled2Unity/Imported/Level1.tiled2unity.xml' but Tiled2Unity files cannot be imported with the WebPlayer[deprecated] platform.
However, You can use Tiled2Unity prefabs imported by another platform.
UnityEngine.Debug:LogWarning(Object)
Tiled2Unity.TiledAssetPostProcessor:UseThisImporter(String) (at Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs:46)
Tiled2Unity.TiledAssetPostProcessor:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs:65)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])`

Anyway to fix this?

**Comment by Seanba** [comment]
Hi goobal60, I think that error explains the problem. If you have a recommendation to make it clearer I'm open to suggestions.

Anyway, you have Unity set to build to the Unity Web Player, and that is no longer supported (and is deprecated by Unity anyhow). Switch to another platform, like Standalone PC, Mac & Linux.

**Comment by Seanba** [comment]
I've made the warning a bit easier to understand. Thankfully with Unity 5.4 the Web Player will be removed so newcomers won't be tricked up by this.
