### ISSUE TITLE
Object layer not to be rendered

### ISSUE THREAD

**Issue by Dennuz666** [Seanba/Tiled2Unity#28]
Hi Sean,

I'm playing around with Object Layers and the CustomTiledImporterForBlocks-script. I once managed to put tiles on the Object Layer and in Unity instead of tile rendering a had my prefabs spawned over there. I think there was a change in Tiled2Unity that nog renders the tiles form the Object Layer, right?

I hope to get my old behaviour back, or i missed something. What could be the case too ;)

Regards,

Dennis

This is the script i'm using for 'replacing' tiles with prefabs:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using UnityEditor;
using UnityEngine;

[Tiled2Unity.CustomTiledImporter]
class CustomTiledImporterForBlocks : Tiled2Unity.ICustomTiledImporter
{

	public void HandleCustomProperties(UnityEngine.GameObject gameObject,
		IDictionary<string, string> props)
	{
		// Does this game object have a spawn property?
		if (!props.ContainsKey("spawn"))
			return;

		// Are we spawning an Appearing Block?
		//if (props["spawn"] != "Coin" && props["spawn"] != "Checkpoint")
			//return;

		// Load the default prefab assest
		// COIN
		string prefabPath = "Assets/Prefabs/Coin.prefab";

		// CHECKPOINTS
		if (props["spawn"] == "Checkpoint") 
		{
			prefabPath = "Assets/Prefabs/Checkpoint.prefab";
		}

		// Instantiate it
		UnityEngine.Object spawn = AssetDatabase.LoadAssetAtPath(prefabPath, typeof(GameObject));

		if (spawn != null)
		{
			GameObject spawnInstance = (GameObject)GameObject.Instantiate(spawn);
			spawnInstance.name = spawn.name;

			// Use the position of the game object we're attached to
			spawnInstance.transform.parent = gameObject.transform;
			spawnInstance.transform.localPosition = Vector3.zero;
		}
	}

	public void CustomizePrefab(UnityEngine.GameObject prefab)
	{
		// Do nothing
	}
}


```

**Comment by Seanba** [comment]
Yes, Tile Objects are now rendered. If you want them removed you can use a
custom property "unity:ignore" set to "visual".

But, probably the easiest for you is to remove the tile object from the
prefab since you already have a custom importer. Adding this code to
your HandleCustomProperties
function should do it:

            // Remove old tile object
            Transform oldTileObject = gameObject.transform.Find("TileObject"
);
            if (oldTileObject != null)
            {
                GameObject.DestroyImmediate(oldTileObject.gameObject);
            }

Best,
Sean

**Comment by Dennuz666** [comment]
Wow! You are fast ;)

I did try to remove the oldTileObject but didn't realise that Find("TileObject") should do the trick. I thought the name was variable and tried some things ending up removing my newly instatiated object too. 

Thanks for the fix, everything is working awesome now.

Regards,

Dennis
