### ISSUE TITLE
Optional 3D Colliders generation

### ISSUE THREAD

**Issue by Niarus** [Seanba/Tiled2Unity#29]
Hello there. 

What do you think about implementing optional generation of 3D colliders? 3D Physics actually performs better than 2D as it is multi-threaded.

I will try to make some research.

Sorry if it is inappropriate place for ideas.

**Comment by Niarus** [comment]
I have tried X-UniTMX and it generates 3D colliders pretty well. [Here is a class](https://bitbucket.org/Chaoseiro/x-unitmx/src/19d024212323/Assets/X-UniTMX/Code/MapExtensions.cs?diff2=19d024212323&at=trunkDev&fileviewer=file-view-default) with collider generation methods, maybe useful.
Sean, I would like to hear from you if it is a good idea at all.

Thank you.

**Comment by Seanba** [comment]
Hi Niarus, I can't see this being a priority anytime soon given the complexity. Are you having significant performance issues that this would adequately address?
This feels a little YAGNI, if you know what I mean. :)

**Comment by Niarus** [comment]
Thank you for answering, I understand you very well, but will add another 5 cents. :)
As my game can have many active objects with colliders (i.e. 2 thousand), even if they are not visible, they place quite a heavy load on the CPU, and as Box2D approach is single-threaded, in this case it loses to 3D PhysX engine, which is multi-threaded.
Will think over other ways to work around this case.

**Comment by Seanba** [comment]
Hi again, Niarus. If it's something you think you really need then you can look into creating a custom importer (that will be invoked by Tiled2Unity automatically). In that importer you can search for instances of PolygonCollider2D components on your prefab and replace them with MeshCollider instances.

I'd recommend you have Tiled2Unity use the option to generate convex polygons in this case as I imagine it would *much* easier to turn those into polyhedrons than it would a concave polygon that may contains holes.
