### ISSUE TITLE
Opacity of Layers

### ISSUE THREAD

**Issue by tikilittle** [Seanba/Tiled2Unity#3]
I created an animation layer and set it to 0.75f opacity and tried to exporting it. When I checked in Unity, it was opaque. Is opacity currently supported with Tiled2Unity?

**Comment by Seanba** [comment]
My apologies for leaving this bug report unattended for two years. Custom opacity has been supported for some time now and since Unity 5.6 it also uses "instancing" so it shouldn't increase the number of draw calls needed.
