### ISSUE TITLE
[Tiled2UnityLite][OSX] whitespaces in paths in command causes failure

### ISSUE THREAD

**Issue by ashwin911** [Seanba/Tiled2Unity#30]
If my file path in %mapfile or the output file path contains a white space, Tiled2UnityLite can't find the file path. Even adding double quotation marks or single plus double quotation marks (eg. '"my/map path"') doesn't work. 

When I add "echo  $0 $* &> tiled2unitylite.log" in the shell script to check the input, I notice that the double quotation marks have disappeared. Which is strange.

**Comment by Seanba** [comment]
Sorry I'm coming to this so late, but the shell script needed to expand the command line variables by using "$@", not $* -- I updated my blog to reflect this.
