### ISSUE TITLE
Tiled2Unity Imported Object Script Error

### ISSUE THREAD

**Issue by RevinKayner** [Seanba/Tiled2Unity#33]
Hello I seem to have an error in the Imported Object script. 
the error reads
 "Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.cs(93,32): error CS0234: The type or namespace name `ImportBehaviour' does not exist in the namespace `Tiled2Unity'. Are you missing an assembly reference?"
the line in question is line 93 

name = Tiled2Unity.ImportBehaviour.GetFilenameWithoutTiled2UnityExtension(name);

I am using Unity 5.3.1 I have a friend using the same version and did not receive the error. 
I've tried multiple reinstallations but receive the same problem. 

Also nothing gets exported into the prefabs folder when I try to import into unity

**Comment by Seanba** [comment]
Are there any other errors in the console output window?

And by any chance do you have the Unity Web Player selected as your build
target? If so, that's the problem -- but I would hope an error in the
output would have spelled that out for you.

(BTW, Press CTRL+SHIFT+B in Unity to see your build settings)

**Comment by RevinKayner** [comment]
Hello. There are no other errors in the output
And yes, the web player was selected for my build target. It appears to be my only option atm. 
Also there was no indication pointing towards the Web player being the problem.I am going to have to redownload unity and make sure the pc, mac, linux build setting is marked  befor I download. Thanks for your timely response! hopefully this fixes things

**Comment by Seanba** [comment]
Hi Revin, I've confirmed switching players (PC, Mac & Linux is a good default choice) will fix the issue. Also, I uploaded version 1.0.4.8 of Tiled2Unity just now. It does a better job of warning you when you have the Web Player activated. Thanks.

**Comment by RevinKayner** [comment]
Just wanted to say that everything works fine now, Thank you for all your help!
