### ISSUE TITLE
Tiled2Unity doesn't work with Unity 4.x :(

### ISSUE THREAD

**Issue by Cellenseres** [Seanba/Tiled2Unity#35]
Hey, I'm using Unity 4.3.7f1 (which is needed to compile for Nintendo Wii U) and I'm not able to use Tiled2Unity :(
When using "Import Unity Package to Import" I'll get:
"Assets/Tiled2Unity/Scripts/Runtime/ImportBehaviour.cs(61,34): error CS1061: Type `UnityEngine.Transform' does not contain a definition for `SetAsFirstSibling' and no extension method `SetAsFirstSibling' of type `UnityEngine.Transform' could be found (are you missing a using directive or an assembly reference?)"

When I try to import my map, there's no prefab, texture or any other thing imported :(

Could you check that out and make Tiled2Unity compatible with Unity 4.3.7f1?

**Comment by Seanba** [comment]
Is Wii U really limited to Unity 4.3? That sounds awful.

What if you comment out that line of code? SetAsFirstSibling isn't
essential for anything -- it's just for setting up the ordering of a
temporary gameobject while importing TMX maps.

Best,
Sean

**Comment by Cellenseres** [comment]
Well, just commenting out this line of code seems to work! :)
Thank you Seanba :)
http://abload.de/img/works08see.jpg

**Comment by Seanba** [comment]
Thanks, Cellenseres. I'll protect against that in a future build of
Tiled2Unity.

Best,
Sean

**Comment by Seanba** [comment]
Tiled2Unity 5.0.6.0 has this small fix. Thanks.
