### ISSUE TITLE
Tiled2Unity Not Working

### ISSUE THREAD

**Issue by BlueNova69** [Seanba/Tiled2Unity#36]
When i transfer the tiled file to unity it just comes in a text file i dont know how to fix i follow all the correct steps but it wont work please help me

**Comment by Seanba** [comment]
Hi there. Have you looked for clues in the Unity output window? I would guess it's because you are using Unity in Web Player mode.

Best,
Sean

**Comment by BlueNova69** [comment]
oh yea i saw somthing about web mode how do i change that

**Comment by Seanba** [comment]
It should be in the warning but press CTRL+SHIFT+B to bring up build settings dialog. Then select "Windows, Mac & Linux" as your build platform.

**Comment by BlueNova69** [comment]
@Seanba hmm yeah when i bring up the page it says page not found
http://download.unity3d.com/download_unity/960ebf59018a/TargetSupportInstaller/UnitySetup-WindowsStandalone-Support-for-Editor-5.3.5f1.exe 
Is there any other links that you used cause i cant seem to find anymore ways to get it

**Comment by Seanba** [comment]
I don't know what you mean by "bring up the page" or where you got that link. It sounds like maybe you didn't include the PC, Mac & Linux target when you installed Unity? In that case reinstalling should help.

What build platforms are available to you? Which one do you eventually intend to make your game for? You don't have to choose PC M&L, you just can't use Unity Web Player.

Best,
Sean

**Comment by BlueNova69** [comment]
@Seanba Ahh yeah re-installing it worked thankyou

**Comment by Seanba** [comment]
For the record, the next version of Unity will remove that cursed Web Player and will default to PC, Mac & Linux Standalone so people shouldn't be tricked up by this much longer.
