### ISSUE TITLE
How to set the  map texture in android and ios platform?

### ISSUE THREAD

**Issue by wangjianpeng** [Seanba/Tiled2Unity#39]
Usually , i heard texture should be set with ETC format in android device, and with PVTC in ios device.
But when i set the etc 8bit on android, the tiled is blur. do you have any idea about this problem ?

**Comment by Seanba** [comment]
What are the dimensions of your texture? I believe they have to be a factor of 4 pixels high and wide. Otherwise, Unity will stretch the texture and that could lead to blurred image.
