### ISSUE TITLE
Can only import one Tiled Map.

### ISSUE THREAD

**Issue by whiskership** [Seanba/Tiled2Unity#40]
Hi I've used Tiled2Unity before with no problem.

I recently started a new project on Unity and I imported one map from Tiled with no trouble. The problem began when I imported a second map for Tiled. When I imported a second map the first one became pink, so I re- imported the first map and then the second one turned pink. And it just keeps going like that.

Do you know any potential fixes to this bug?

Using Unity 5.3.5 p2 and most recent version of Tiled2Unity

**Comment by whiskership** [comment]
Fixed by resetting Unity. Sorry.

**Comment by Seanba** [comment]
By any chance were you exporting into Unity as the editor was "playing"
your scene? If not, and you see this bug again, please let me know. I
normally wouldn't expect you to have to restart Unity.

Best,
Sean

**Comment by whiskership** [comment]
Hi I thought the problem was solved but it actually isn't.

The editor wasn't playing when exporting into Unity. 

Every time I export a map into Unity all the other maps turn pink. The only way to fix it is by restarting Unity and all the maps are back to normal. But if export another map they all turn pink again.

I've tried exporting into different projects and exporting different maps and the problem continues.

**Comment by Seanba** [comment]
Hmmm are your maps using the same texture? One recent "feature" is that materials are recreated during import so maybe that's causing this?

**Comment by whiskership** [comment]
Yes they are using the same texture. And if I go into the Tiled2Unity folder there is only one material for all the maps which makes sense.

**Comment by paulboutros** [comment]
Hi Seanba! Thanks for the wonderful work! I have been using an old version of Tile2Unity for few week and it was working perfectly until  the 1.0.6.0 version.What's happening is that when a map is imported (or re imported) ALL other map have their material component deleted or removed

**Comment by seanb-22ct** [comment]
Can you guys try updating your Unity projects with this Tiled2Unity package? It should take care of this problem (although you may have to restart Unity one more time for maps that were broken previously).

https://dl.dropboxusercontent.com/u/44608487/Tiled2Unity.1.0.6.0.unitypackage

If I can get confirmation it works for you guys then I'll release the fix to the wild. Thanks.

**Comment by Seanba** [comment]
Try this Unity package in your project and see if it fixes it.

https://dl.dropboxusercontent.com/u/44608487/Tiled2Unity.1.0.6.0.unitypackage

This should create the materials *only* when needed, otherwise it will overwrite what is already there but in a way that keeps links from prefabs valid.

**Comment by paulboutros** [comment]
this following line (inside the  "CreateOrReplaceAsset"  function )gets an error: 
T existingAsset = AssetDatabase.LoadAssetAtPath<T>(path);

Assets/Tiled2Unity/Scripts/Editor/ImportUtils.cs(133,46): error CS1501: No overload for method `LoadAssetAtPath' takes `1' arguments

**Comment by seanb-22ct** [comment]
What version of Unity are you using, Paul?

**Comment by paulboutros** [comment]
5.0.1.11919

**Comment by Seanba** [comment]
That override must be a newer addition to Unity then. Do you mind replacing
the line that fails to compile with this?

T existingAsset = (T)AssetDatabase.LoadAssetAtPath(path, typeof(T));

Thanks,
Sean

**Comment by paulboutros** [comment]
Well the miracle happened. The bug is gone I re-imported 3 maps sharing the same material and it all works properly!
Awesome.
Thanks,

Paul

**Comment by Seanba** [comment]
Thank you, Paul. I will push out the version that supports current and past versions of Unity soon and close the bug then.

**Comment by whiskership** [comment]
Hey Sean the Unity package worked perfectly for me with no errors and didn't have to change any code. I can now import new maps without the other ones turning pink (they are all using the same texture same as before). Using Unity 5.3.5 p2. Thanks a lot!
