### ISSUE TITLE
Importing two prefabs that use the same tileset image makes one prefab lose its material reference

### ISSUE THREAD

**Issue by dkatch** [Seanba/Tiled2Unity#41]
When you import a prefab that uses the same tileset as another prefab, a new material is created and the old prefab loses the reference to its material.

This can be fixed by checking to see if the material already exists in the asset database, and if it does, to not create a new one.

**Comment by Seanba** [comment]
Hi dkatch. This was a bug with version 1.0.6.0 that was fixed with version 1.0.7.0

Best,
Sean
