### ISSUE TITLE
Exporting with convex colliders throws: Error marking neighbors -- t doesn't contain edge p1-p2!

### ISSUE THREAD

**Issue by SugoiDev** [Seanba/Tiled2Unity#43]
I just came accross this bug when using the "generate convex colliders" option in the exporter tool on Windows 10.

My configurations are as follows:
* Tiled 0.16.1
* Tiled2Unity 1.0.7.2

**How to reproduce**
* Use this small reproduction map: [TiledRepro.zip](https://github.com/Seanba/Tiled2Unity/files/340715/TiledRepro.zip)
* Setup Tiled2Unity and try to export the map

**Export tool messages during export**

    Command: E:/TiledRepro/Repro.tmx
    --------------------------------------------------------------------------------
    Arguments summary
    Succeeded: 0
    Warnings: 0
    Errors: 0
    --------------------------------------------------------------------------------
    Opening E:\TiledRepro\Repro.tmx ...
    Parsing map root ...
    Parsing tileset elements ...
    Parse internal tileset 'Common' (gid = 1) ...
    Added 6 tiles
    Parse tile data (gid = 1, id 0) ...
    Parsing objects in object group ''
    Parsing object ...
    Parse tile data (gid = 2, id 1) ...
    Parsing objects in object group ''
    Parsing object ...
    Parse tile data (gid = 3, id 2) ...
    Parsing objects in object group ''
    Parsing object ...
    Parsing layer elements ...
    Parse Tile Layer 1 layer data ...
    Parsing layer data as base64 string ...
    Parsing objectgroup elements ...
    Map details: { "0" size = 3x3, tile size = 16x16, # tiles = 6, # layers = 1, # obj groups = 0 }
    Parsed: E:\TiledRepro\Repro.tmx 
    --------------------------------------------------------------------------------
    Loading summary
    Succeeded: 1
      Parsed: E:\TiledRepro\Repro.tmx 
    Warnings: 0
    Errors: 0
    --------------------------------------------------------------------------------
    Exporting 'E:\TiledRepro\Repro.tmx' to 'E:\TiledRepro\Tiled2Unity'
    Compiling tiled2unity file: Repro.tiled2unity.xml
    Writing 'mesh_0001' mesh group
    Writing face vertices
    Writing face uv coordinates
    ImportTexture : will import 'e:\TiledRepro\Common.png' to E:\TiledRepro\Tiled2Unity\Textures
    Gathering prefab data ...
    Clipping '' polygons: 0%
    Clipping '' polygons: 100%
    Error marking neighbors -- t doesn't contain edge p1-p2!
    --------------------------------------------------------------------------------
    Exporting summary
    Succeeded: 0
    Warnings: 0
    Errors: 1
      Error marking neighbors -- t doesn't contain edge p1-p2!
    --------------------------------------------------------------------------------

---

With Tiled2Unity 1.0.6.0, there's an exception window output as well that might provide more insight:

**Exception window (for Tiled2Unity 1.0.6.0)**

    See the end of this message for details on invoking 
    just-in-time (JIT) debugging instead of this dialog box.

    ************** Exception Text **************
    System.Exception: Error marking neighbors -- t doesn't contain edge p1-p2!
       at Poly2Tri.DelaunayTriangle.MarkNeighbor(TriangulationPoint p1, TriangulationPoint p2, DelaunayTriangle t)
       at Poly2Tri.DTSweep.Fill(DTSweepContext tcx, AdvancingFrontNode node)
       at Poly2Tri.DTSweep.PointEvent(DTSweepContext tcx, TriangulationPoint point)
       at Poly2Tri.DTSweep.Sweep(DTSweepContext tcx)
       at Poly2Tri.DTSweep.Triangulate(DTSweepContext tcx)
       at Poly2Tri.P2T.Triangulate(PolygonSet ps)
       at Tiled2Unity.ConvexPolygonSet.GetTriangleListFromClipperSolution(PolyTree solution)
       at Tiled2Unity.LayerClipper.<SolutionPolygons_Simple>d__7.MoveNext()
       at Tiled2Unity.TiledMapExporter.AddPolygonCollider2DElements_Convex(PolyTree solution, List`1 xmlList)
       at Tiled2Unity.TiledMapExporter.CreateCollisionElementForLayer(TmxLayer layer)
       at Tiled2Unity.TiledMapExporter.CreatePrefabElement()
       at Tiled2Unity.TiledMapExporter.Export(String exportToTiled2UnityPath)
       at Tiled2Unity.Tiled2UnityForm.buttonExport_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

    ************** Loaded Assemblies **************
    mscorlib
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
    ----------------------------------------
    Tiled2Unity
        Assembly Version: 1.0.6.0
        Win32 Version: 1.0.6.0
        CodeBase: file:///t:/Tiled2Unity/Tiled2Unity.exe
    ----------------------------------------
    System
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
    ----------------------------------------
    System.Windows.Forms
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
    ----------------------------------------
    System.Drawing
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
    ----------------------------------------
    System.Configuration
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    ----------------------------------------
    System.Core
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
    ----------------------------------------
    System.Xml
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
    ----------------------------------------
    Accessibility
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
    ----------------------------------------
    System.Xml.Linq
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
    ----------------------------------------
    PresentationCore
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
    ----------------------------------------
    WindowsBase
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
    ----------------------------------------

    ************** JIT Debugging **************
    To enable just-in-time (JIT) debugging, the .config file for this
    application or computer (machine.config) must have the
    jitDebugging value set in the system.windows.forms section.
    The application must also be compiled with debugging
    enabled.

    For example:

    <configuration>
        <system.windows.forms jitDebugging="true" />
    </configuration>

    When JIT debugging is enabled, any unhandled exception
    will be sent to the JIT debugger registered on the computer
    rather than be handled by this dialog box.

**Comment by Seanba** [comment]
Thank you for the exceptional report with repro steps and a Tiled example. I have been able to reproduce the behavior and I'm thinking of ways to solve it.

**Comment by SugoiDev** [comment]
Thanks for replying! 

Since I don't have the time to investigate the issue myself right now I'll try to at least contribute with as much information as I can get whenever I encounter an issue.


Thanks again!

**Comment by Seanba** [comment]
Version 1.0.7.3 fixes this. FWIW, during convex composition that complex polygon is triangulated and convex polygons are formed from that triangulation. I had to replace the polygon triangulation library with something that allowed holes to intersect with an polygon edge. Thanks for the bug report.

**Comment by SugoiDev** [comment]
That's great to read!

Thanks!
