### ISSUE TITLE
Mesh Renderer May have Some Problem.

### ISSUE THREAD

**Issue by zhe13** [Seanba/Tiled2Unity#44]
Unity 5.4
When I import tiled maps into Unity, I find that there are color lines between tiles.
May be change to Sprite Renderer will solve it?

**Comment by Seanba** [comment]
What you are seeing are seams and that's a common 3D problem with vertices that share an edge but with different texture coordinates. I try my best to make up for them in Tiled2Unity but under some conditions (camera position, and especially if lighting is being used) they are prominent.

The best way to handle seams is to have a "border" around each tile that makes up for the texture sampler getting out of bounds. You can read about a solution for that here: http://www.firebelly.net/post/114529965784/tile-gaps-using-unity-5-and-tiled2unity
