### ISSUE TITLE
Objects position incorrect after Tiled2Unity process

### ISSUE THREAD

**Issue by janisc** [Seanba/Tiled2Unity#45]
I am using Tiled 0.16.1 and Tiled2UnityMac 1.0.7.3 both on Mac. I work with isometric map. On top of the map I add objects, which are tileset type of "Collection of images".

In Tiled2UnityMac the preview shows same incorrect placements of bitmaps in objects layer that will show in Unity too. Attached is a small Tiled project that shows the problem. Observe the position of the house and the train car in Tiled and in Tiled2Unity preview.

[Bug report.zip](https://github.com/Seanba/Tiled2Unity/files/347770/Bug.report.zip)
Here are screenshots that show the problem.
Tiled screenshot (correct)
![tiled screenshot](https://cloud.githubusercontent.com/assets/1122039/16586092/c112b1d8-42cc-11e6-9079-2f4e50dd3fca.png)
Tiled2Unity preview screenshot (incorrect)
![tiled2unitypreviewscreenshot](https://cloud.githubusercontent.com/assets/1122039/16586101/c9139d66-42cc-11e6-8622-fb1929e6657a.png)

**Comment by Seanba** [comment]
Thanks for the complete bug report and repro. I've found the problem and will provide a fix for this later today.

**Comment by janisc** [comment]
Great! Thanks a lot!

**Comment by Seanba** [comment]
Version 1.0.7.4 of Tiled2Unity was just uploaded which contains the fix for this.

https://seanba.itch.io/tiled2unity

Thanks again for the bug report.
