### ISSUE TITLE
Stretched objects seem to generate misplaced colliders

### ISSUE THREAD

**Issue by SneakyMax** [Seanba/Tiled2Unity#52]
I just started messing around with Tiled and Tiled2Unity, was looking into how colliders were generated for Object Layer objects. 

From a quick glance, it seems that the collider is misplaced when an object is stretched:

Not stretched object:

![2016-07-12 16_59_17-settings](https://cloud.githubusercontent.com/assets/342540/16787645/a7f299e4-4852-11e6-878e-aae0f5655694.png)

Stretched object:

![2016-07-12 16_59_47-start](https://cloud.githubusercontent.com/assets/342540/16787644/a7f1d4e6-4852-11e6-98c5-e1e240eb0e76.png)

**Comment by seanb-22ct** [comment]
Thanks, Max. I have reproduced your bug and will be looking at a fix. Please note I'm just about to head out of town until Monday so may not have a proper fix until next week.

**Comment by Seanba** [comment]
Thanks for the bug report, Max. I'll be out of town most of this week so I hope to get a fix for this out early next week.

**Comment by SneakyMax** [comment]
No problem, not even something we need, just randomly found it!

**Comment by Seanba** [comment]
This is fixed with version 1.0.7.6. Thanks again for letting me know. It was cool of you to do so considering you didn't need this functionality. :)
