### ISSUE TITLE
Question: How to attach Custom MonoBehaviour Script to Tiled Object?

### ISSUE THREAD

**Issue by HDNua** [Seanba/Tiled2Unity#53]
First, thank you for distributing this amazing assist tool.
I'm also one of the big fan of the greatest game Rockman(Megaman), so I'm making a fan game (X-series) too.

I want to attach custom script to imported GameObject, but I couldn't find about how to do this.
In additional, I want to set default value of it. (want to use custom properties)

Since it is not enough to explain my situation because of my poor English, I'll explain more in detail.

<img src="https://lh3.googleusercontent.com/-mmGsZhHqp8c/V4iKDvJG9aI/AAAAAAAAAIM/6pCvycYOPiAmYNPHV2GiopbWF9U1O4z9wCCo/s1152/Q.png">

I wrote code class "CameraZone5Script". This class has several public boolean fields: _isTopBounded, _isLeftBounded, _isRightBounded, _isBottomBounded, etc.
In Tiled, I created Object Layer "CameraZone", created and checked custom properties like this.

<img src="https://lh3.googleusercontent.com/-og8M9iJMKdw/V4iLCPhDUiI/AAAAAAAAAIg/KfY-V-Mj9lEAtl4jCEOdljR3OK2KOCA2wCCo/s1152/Q2.png">

But it is not applied appropriately in Unity (5.3.5), so please, I want to hear some advices.

Again, thanks to your good program.

**Comment by Seanba** [comment]
Hi there. Here's what you'll need to achieve your goals.

Make sure your custom properties Objects Types Xml file is known to Tiled2Unity (http://www.seanba.com/object-type-support.html)
Write a Custom Importer script in your Unity project that takes properties from Tiled and shoves them into components. Make sure that script lives in an 'Editor' folder (it's a common mistake). I talk more about Custom Importers here: http://www.seanba.com/megadadadventures.html

In the meantime, I'll give some thought to making this more automated given your example. (Will be several weeks before I make progress on it though.)

**Comment by HDNua** [comment]
I'll try it. Thanks for reply. :+1: :)
