### ISSUE TITLE
Animation problem when animating with different amount of frames

### ISSUE THREAD

**Issue by lrasomattos** [Seanba/Tiled2Unity#54]
Hi!!
There is a bug (I believe) when we have tiles with different amount of frames in the same layer.

For example, I have in my tileset: animation A with 3 frames and animation B with 4 frames..

The importer generates 4 objects.. 3 objects containing meshes for the first 3 frames of A and B, and 1 object containing the last frame of B.

When animation A loops for the 1st frame, animation B is in the 4th frame. At this time both meshes are turned on. Which doesn't make much sense.. It looks right for A, but B is messed up.

I don't really know the best way to solve this. But I'm still happy with the new animation importing system.. We had done lots of optimizations in the last one, but now it looks much more efficient.

**Comment by Seanba** [comment]
Hi there. I've been able to reproduce this bug and will try to get a fix out in a couple of days. Thanks for letting me know.

**Comment by Seanba** [comment]
Version 1.0.7.6 fixes this. Thank again for the bug report.
