### ISSUE TITLE
Export scale not changed

### ISSUE THREAD

**Issue by rwols** [Seanba/Tiled2Unity#58]
On OSX, when having a certain export scale, and having exported a prefab, then changing the export scale in Tiled2UnityMac, the actual export scale is not updated to the newly set export scale in the GUI.

**Comment by Seanba** [comment]
Hi rwols, have you tried hitting "ENTER" or "RETURN" after changing the value?

**Comment by rwols** [comment]
Yes, this works. Sorry this is ancient. I'll close the issue.
