### ISSUE TITLE
Question: Exported Map is blurry; May I ask how I can fix this?

### ISSUE THREAD

**Issue by HDNua** [Seanba/Tiled2Unity#59]
Again, thank you for distributing this amazing assist tool.

I exported map with Tiled2Unity, but result is not quite good...
I mean, it works but I want it to be more... clearly.

This is my fan-game's intro stage map.
<img src="http://i.imgur.com/2VnYzMY.png">

and this is result that imported in Unity.
<img src="http://i.imgur.com/4VYWaKz.png">
<img src="http://i.imgur.com/kIs3aY4.png">

(I can send you my .tmx file if you want to check it yourself)
You can see that the original image and sprites of objects(Rockman X, Mettool, Walkcannon) inside game are quite clear, while background image is not. (It's blurry, fuzzy, scattered, and unfocused..? I couldn't found the word that explain this situation exactly)

And, I found about post that this might be because the image that I use was too big.
http://discourse.mapeditor.org/t/large-tiled-maps-look-unfocused-when-imported-to-unity/219

But I'm not good at English and I couldn't find out how to fix this problem.

So, I ask for you how I can solve this problem.
Sincerely, I really appreciate you! :)

Unity Version: 5.4.0

End of issue.

**Comment by Seanba** [comment]
Hi HDNua, what are the dimensions of the texture you are using for your background? You'll want to make sure your Max Size value in the Texture Importer settings will accommodate a texture of that size ...

![image](https://cloud.githubusercontent.com/assets/6980630/18280240/ff00fe00-741d-11e6-900d-6d78985e3c31.png)

For most platforms, the Max Size caps at 8192, so if your texture is larger than that then you'll need to break it down into smaller pieces.

BTW, those are some great pics. And if there's one thing we need more of, it's Megaman type games.

**Comment by HDNua** [comment]
1. You mean that the texture in "Assets/Tiled2Unity/Textures/<target_texture>"!
I was wondering that where I can see the texture importer setting inspector a while... silly me.
(I just clicked child object in "Tile Layer" and the child had only "Transform" component)

I changed the Max Size to 8192, and now It became much better!

2. That's my coworker's work. It's pretty nice.

3. It might be a silly question...
What do you mean 'the thing' that we need more of exactly? (blame for my poor English... T.T)

Anyway, Thanks for your help again. :)

**Comment by Seanba** [comment]
> What do you mean 'the thing' that we need more of exactly? 

Oh sorry, it's an expression that is lost in translation. What I really mean to say is that I love Megaman games and I would like to see more games like that created. :)

**Comment by HDNua** [comment]
Aha.. I got it. lolololol
