### ISSUE TITLE
Move some comments to wiki

### ISSUE THREAD

**Issue by pedzed** [Seanba/Tiled2Unity#6]
Examples and instructions should be moved to a wiki. The bad thing about putting it inside the source code is that people have to look for it. In a wiki, everything is better organized.

An example is [`ICustomTiledImporter.cs`](https://github.com/Seanba/Tiled2Unity/blob/fe65be5e72c275bd19e5dc995737c5f0603d7e18/unity/Tiled2Unity/Scripts/Editor/ICustomTiledImporter.cs#L22-L43) containing the following code:

````cs
// Examples
/*
[Tiled2Unity.CustomTiledImporter]
class CustomImporterAddComponent : Tiled2Unity.ICustomTiledImporter
{
    public void HandleCustomProperties(UnityEngine.GameObject gameObject,
        IDictionary<string, string> props)
    {
        // Simply add a component to our GameObject
        if (props.ContainsKey("AddComp"))
        {
            gameObject.AddComponent(props["AddComp"]);
        }
    }


    public void CustomizePrefab(GameObject prefab)
    {
        // Do nothing
    }
}
*/
```

**Comment by aggsol** [comment]
Those are the example that are documented on the website like here http://www.seanba.com/megadadadventures.html But I agree that moving(adding information to the wiki here is a good idea.

**Comment by Seanba** [comment]
Tiled2Unity is proving to be more popular than I thought it would be and as such I'll be putting up some proper documentation soon. Thanks.
