### ISSUE TITLE
Possibility to import Materials in Resource folder

### ISSUE THREAD

**Issue by dpavon** [Seanba/Tiled2Unity#64]
Hi, sorry to trouble you with more procedurally generation-based issues, but I think I might not be the only one who would like this feature.

The idea is: I'm importing maps with unity:resource = True (as discussed on previous issues) to have them on a Resources folder, where I can instantiate them whenever needed.

This time, however, I would like to change the "tileset" of the map on execution. For this, I created a map with all possible tilesets, so that I guarantee thay they are created by Tiled2Unity as a Material and Texture.  Materials are there, but I cannot change them in runtime as they do not exist on a "Resources" folder.

I guess code would be very similar to that change I requested back then with unity:resource. I went and changed method "GetMaterialAssetPath" so that it would always save them on a "Resources" folder. However, best approach would be the same as with Prefabs, so adding an "extraPath" variable to mehtod "GetPrefabAssetPath" would work. 

Although I don't think a "property" per map is the way to go this time. If one map uses tileset A with that property, and other does not have the property, but uses the tileset, we would end up with duplicated materials. Maybe a checkbox inside Tiled2Unity.exe?

Thanks again!

**Comment by Seanba** [comment]
Hi Daniel, sorry for the late reply.

What if I were to put materials in resource folders automatically when you
decide to do so for the prefab? If the prefab is going to be in Resources
then we might as well do the same for materials too, right?

**Comment by dpavon** [comment]
Yeah sure. I guess we can assume people go either fully procedural or for static content, but not middle grounds, so it could be enabled for both Prefabs and Materials.

Thanks!

**Comment by Seanba** [comment]
Sorry I'm late on the update. But version of 1.0.9.1 of Tiled2Unity fixes this so that materials are placed in a Resources folder if the prefab is itself a resource.
