### ISSUE TITLE
Problem when exporting a map

### ISSUE THREAD

**Issue by Aupuma** [Seanba/Tiled2Unity#67]
Hi, I have tried to export one of my own maps, (64x64 pixels) and the map isn't centered. I have tried with other maps from different places and there is no problem. 
![captura](https://cloud.githubusercontent.com/assets/22346231/20625164/e0fcc2c6-b311-11e6-8502-61f22e578c6e.PNG)
![dsf](https://cloud.githubusercontent.com/assets/22346231/20625177/e710b9b0-b311-11e6-9f86-49c2de9a452b.PNG)

**Comment by Seanba** [comment]
In Tiled, check your "Tile Layer" properties for horizontal or vertical offset. Also, check your "Tileset" properties for "Drawing Offset". My guess is one or more of these values is set to a non-zero number.

**Comment by Aupuma** [comment]
Solved!!! It was the offset of the tile layer, I don't know why it was set to 80 for horizontal and 40 for vertical !! Thanks a lot man!!

**Comment by Aupuma** [comment]
I have a second problem, when the map gets exported into Unity, there are some fadings in the edges between some of the tiles. I have disabled antialiasing as some people have had a similar problem, but there is no difference.
![captura](https://cloud.githubusercontent.com/assets/22346231/20648510/89e684e2-b4a9-11e6-8a03-9eb06a3d0d01.PNG)
![fdsf](https://cloud.githubusercontent.com/assets/22346231/20648511/8da3e43a-b4a9-11e6-8257-98cfcd852832.PNG)
![sdfsdfsfd](https://cloud.githubusercontent.com/assets/22346231/20648512/930fbf84-b4a9-11e6-8cb2-d774f0d8e16a.PNG)

**Comment by Aupuma** [comment]
Finally solved, I changed some import settings of the image and switched off pixel snap in the material
