### ISSUE TITLE
Path issues on script when importing to unity

### ISSUE THREAD

**Issue by Doctor-Holmes** [Seanba/Tiled2Unity#70]
A few days ago I updated to Unity 5.5 and when importing tiled2unity to unity I get a lot of errors 

all of them are related to Path

Error	CS0117	'Path' does not contain a definition for 'GetFullPath'	
Error	CS0117	'Path' does not contain a definition for 'GetDirectoryName'
Error	CS0117	'Path' does not contain a definition for 'DirectorySeparatorChar'	
Error	CS0117	'Path' does not contain a definition for 'DirectorySeparatorChar'	corgiborg.CSharp.Editor	
Error	CS0117	'Path' does not contain a definition for 'GetFileNameWithoutExtension'	
Error	CS0117	'Path' does not contain a definition for 'GetFileNameWithoutExtension'
Error	CS0117	'Path' does not contain a definition for 'GetFileNameWithoutExtension'
Error	CS0117	'Path' does not contain a definition for 'GetFileName'

**Comment by Seanba** [comment]
Path is part of the System.IO namespace and is standard fare in C# code. Do you have another class named 'Path' in your project somewhere that is name-colliding with it?

**Comment by Doctor-Holmes** [comment]
I'm a moron, thank you

**Comment by Seanba** [comment]
FWIW, I changed the code so that the Path name collision will not happen again. (At least not in Tiled2Unity.)

**Comment by chaddivine** [comment]
Hi I am having the same issue. However, I am not a dev. May I ask how you located the conflict among your vast amount of scripts? I searched path in assets, but it only finds folders and files not what's in each script so how can I find this conflict?
