### ISSUE TITLE
Libs deprecated in several scripts on Unity (5.5.x).

### ISSUE THREAD

**Issue by arthurvasconcelos** [Seanba/Tiled2Unity#71]
- Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(201,29): warning CS0618: `UnityEditor.TextureImporter.lightmap' is obsolete: `lightmap Property deprecated. Check [[TextureImporterSettings.textureType]] instead. Getter will work as expected. Setter will set textureType to Lightmap if true, nothing otherwise.'

- Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(203,29): warning CS0618: `UnityEditor.TextureImporter.grayscaleToAlpha' is obsolete: `Use UnityEditor.TextureImporter.alphaSource instead.'

- Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(204,29): warning CS0618: `UnityEditor.TextureImporter.linearTexture' is obsolete: `linearTexture Property deprecated. Use sRGBTexture instead.'

- Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(207,78): warning CS0618: `UnityEditor.TextureImporterGenerateCubemap.None' is obsolete: `This value is deprecated (use TextureImporter.textureShape instead).'

- Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(210,67): warning CS0618: `UnityEditor.TextureImporterFormat.AutomaticTruecolor' is obsolete: `Use textureCompression property instead'

- Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs(210,29): warning CS0618: `UnityEditor.TextureImporter.textureFormat' is obsolete: `textureFormat is not longer accessible at the TextureImporter level. For old 'simple' formats use the textureCompression property for the equivalent automatic choice (Uncompressed for TrueColor, Compressed and HQCommpressed for 16 bits). For platform specific formats use the [[PlatformTextureSettings]] API. Using this setter will setup various parameters to match the new automatic system as well possible. Getter will return the last value set.'

**Comment by InMeVa** [comment]
I have the same issue, any idea on the timeline when it is going to be fixed?

**Comment by Seanba** [comment]
I had fixed this a while ago in the released binary but had not updated Github. Sorry about that. It should all be good now.
