### ISSUE TITLE
unity:ignore=collision not working

### ISSUE THREAD

**Issue by richayrich** [Seanba/Tiled2Unity#73]
I'm using the "unity:ignore" custom property, with value set to "collision", in an object layer. However, after exporting, each game object within the object layer still has a collider. Am I using this wrong?

**Comment by Seanba** [comment]
Hi there. Looks like you've found a bug. I've just put up a new version of
Tiled2Unity (1.0.9.4) that should have this fixed now. Let me know if that
works for you. (Make sure to update your Unity-side scripts with the new
version)

**Comment by richayrich** [comment]
That works perfectly. Thanks! 👍
