### ISSUE TITLE
Strange issue when importing some .tmx files

### ISSUE THREAD

**Issue by armanafghani** [Seanba/Tiled2Unity#74]
First, just want to say I've been using Tiled2Unity for the past couple months now and it's absolutely fantastic. Thanks so much for making this!

I'm hitting a strange error when I try to import one of my .tmx files. The Tiled2Unity shows that the export to Unity is successful, however when I go into unity, the corresponding prefab is not loaded in the Prefab folder. Moreover, a new gameobject titled "__tiled2unity_importer" is created in my scene. When I run the scene, I get an error in the console saying: 

ImportBehaviour based on 'Assets/Tiled2Unity/Imported/{file_name}.tiled2unity.xml' left in scene after importing. Check if import was successful and remove this object from scene __tiled2unity_importer
UnityEngine.Debug:LogError(Object)
Tiled2Unity.ImportBehaviour:Update() (at Assets/Tiled2Unity/Scripts/Runtime/ImportBehaviour.cs:148)

The Tiled2Unity logs outputted the following on export:
Exporting summary
Succeeded: 1
  Succesfully exported: /Users/armanafghani/Documents/JetPack/Assets/Tiled2Unity/Imported/{file_name}.tiled2unity.xml
  Vertex Scale = 0.01
  Object Type Xml = <none>
Warnings: 0
Errors: 0

I did some due diligence and checked the code at Tiled2Unity/Scripts/Runtime/ImportBehaviour.cs:148, and it appears that the error is caused by import behaviour leaking into runtime? How would I go about fixing this issue?

**Comment by Seanba** [comment]
Hi Arman, try deleting the __tiled2unity_importer object and re-import. If
an error still remains would you mind sending me a Unity package of your
project? It sounds like there might be something special about your map
that I'm not handling properly.

**Comment by Seanba** [comment]
It's been over a month so closing for now. Arman, if you're still have trouble let me know.
