### ISSUE TITLE
Background Color not exporting in maps

### ISSUE THREAD

**Issue by chardish** [Seanba/Tiled2Unity#75]
Looks like if you set the background color of a Tiled map in the Map Properties inspector, that color isn't getting exported into the XML that the Unity plugin can see - as a result, the color data is inaccessible in Unity.

**Comment by chardish** [comment]
I created a pull request that fixes this: #76

**Comment by chardish** [comment]
Hey @Seanba, is this something you could take a look at? Thanks : )

**Comment by Seanba** [comment]
Hi Evan. Have you tested this? It looks to me like it will save out the
background color as a System.Drawing.Color string representation which is
almost certainly what you don't want. Also, in what way would this be used
in Unity? I'm not sure the background color would useful but I'm open to
suggestions. :)

**Comment by chardish** [comment]
Hmm, what would you recommend for representing a color in XML?

As for the practical applications: it's fairly common in 2D games for maps that are smaller than the screen space to have a background color for artistic effect. 

Examples:
![Example 1](https://cloud.githubusercontent.com/assets/1151294/22514216/74db8a06-e853-11e6-8bcf-b140088e821d.png)
![Example 2](https://cloud.githubusercontent.com/assets/1151294/22514259/9a75bb88-e853-11e6-9d4e-7b949677dd1e.jpg)
![Example 3](https://cloud.githubusercontent.com/assets/1151294/22514242/8d6b2d42-e853-11e6-9c14-c645ecf75580.jpg)


It is possible to achieve this using a flat-color background image (or a layer of flat-color tiles), but in Unity I prefer to set the clear flags of the camera that renders the tilemap to "Solid Color" and pick the background color that way - there's much less overhead.

**Comment by Seanba** [comment]
I wouldn't use solid-color tiles to apply the background color effect.
However, many usages of Tiled2Unity have multiple maps in the same Unity
scene. In that scenario, which map sets the background color? I guess I
could just make color available and you could choose to use it (or not) as
you see fit.

**Comment by chardish** [comment]
Well, if the user is displaying multiple maps at the same time in her game, it's up to her to determine what order they need to be layered in the scene, right? I could think she could just determine what background color (if any) would apply for a given scene.

**Comment by Seanba** [comment]
I have it saved as an HTML color that gets automatically imported into a UnityEngine.Color when the map prefab is created. This will be in the next version of Tiled2Unity, which I plan to release sometime soon (next couple of days).

**Comment by chardish** [comment]
Fantastic! Thanks, Sean!

**Comment by Seanba** [comment]
Tiled2Unity 1.0.9.5 adds the BackgroundColor setting to the TiledMap component. Thanks for the suggestion.
