### ISSUE TITLE
Cannot set current directory error

### ISSUE THREAD

**Issue by Danisuper** [Seanba/Tiled2Unity#77]
Hello, I'm facing a boring error. In my assets folder (a folder different from unity's one) I save all my sprites, tilesets with collision masks and levels. At first when my game was small and with only a test map and a tileset they all were in the same "root" folder wich is the assets folder (again, it is different from unity's one). But now I added a lot of sprites and tilesets so I organized everything in folders, and now when I try to import to unity a map with tiled2unity it throws me the error "Cannot set current directory. Does not exist: C:\Users\Me\Desktop\assets\Game\tilesets\tileset_terreni.tsx" and the strangest thing is that the tileset is is not in the folder tilesets because it just doesn't exist, take a look:

![Screenshot](http://i.imgur.com/KvFckVI.jpg)

(now the levels and the tilesets are on the root folder but before that they were in the folder "tilesets" and "levels", I have put them there only to see if it worked)
So how can I solve this error? 
Thank you very much for having made Tiled2Unity, it saved me countless hours of time! 😃

**Comment by Seanba** [comment]
Hi Danisuper. It looks like tileset_terreni.tsx was moved but one of your map files still references it in the old location.
