### ISSUE TITLE
GetExistingMaterialAssetPath method runs into issues with AssetDatabase.FindAssets for Materials...

### ISSUE THREAD

**Issue by datahead8888** [Seanba/Tiled2Unity#78]
Upon upgrading to Unity 5.5.0f3 Personal, I also upgraded Tiled2Unity (to version 1.0.9.4) and Tiled (to 0.18.0) in order to resolve warnings about the Unity API's I was getting.

However, I discovered that when I reimported my Tiled levels, it was using the wrong Tileset for a lot of tiles.  I debugged the Tiled2Unity importing code and found an issue in the following method:
https://github.com/Seanba/Tiled2Unity/blob/96051cf01c427d2c062aa7caa68cadacc153afda/unity/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.cs#L95-L108

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~c#
partial class ImportTiled2Unity : IDisposable
...

public string GetExistingMaterialAssetPath(string file)
{
            // The named material may be in a Ressources folder or not so we use the asset database to search
            string name = Path.GetFileNameWithoutExtension(file);
            string filter = String.Format("t:material {0}", name);
            string folder = this.assetPathToTiled2UnityRoot + "/Materials";
            string[] files = AssetDatabase.FindAssets(filter, new string[] { folder });
            if (files.Length > 0)
            {
                return AssetDatabase.GUIDToAssetPath(files[0]);
            }

            return "";
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This method was being called with a value of "GroundTileSet" for parameter file.  The filter generated was, "t:material GroundTileSet". However, two entries were being returned from AssetDatabase.FindAssets: Assets/Tiled2Unity/Materials/BackgroundTileSet.mat and Assets/Tiled2Unity/Materials/GroundTileSet.mat (in order).  Since the method is written to return the first element in the array, it incorrectly returns the full path containing BackgroundTileSet.mat, resulting in an incorrect tile set assignment.

Obviously, Assets/Tiled2Unity/Materials/BackgroundTileSet.mat does not match the name of GroundTileSet.  It looks like a possible bug in Unity.  However, if this behavior is consistently encountered in Tiled2Unity, it probably would need a workaround until Unity no longer does this.  The issue probably needs to be reported on the Unity forums as an apparent bug.

I was able to work around this in my project by adding a loop to search through the array of file entries and looking for an entry with "/" followed by the name followed by ".mat".

Does anyone else see similar behavior here?  You of course would need multiple tile sets in a Tiled scene to run into this problem.

**Comment by Seanba** [comment]
Thanks for this, Chris. I am away from my development environment for the
next couple of days but this is an oversight on my part that I'll likely
fix by taking your lead.

**Comment by Seanba** [comment]
Tiled2Unity 1.0.9.5 fixes this issue. Thanks for reporting the bug.

**Comment by datahead8888** [comment]
I just upgraded to Tiled2Unity version 1.0.12.3 and did not have this issue again.  Thank you for fixing it.
