### ISSUE TITLE
Depth buffering issue

### ISSUE THREAD

**Issue by so3arbelnox** [Seanba/Tiled2Unity#79]
I'm having a few issues getting depth buffering to work. For the SpriteDepthInMap script, what value is "Placed on Layer Index" supposed to be set to?  My impression is the layer that the sprite would be interacting with, however this doesn't seem to work. If I set it to the layer multiplied by the number of tiles in height, it will work in that general section of the map but not when moving too far upwards or downwards.

Another post goes into a lot more detail about this issue:
http://discourse.mapeditor.org/t/depth-buffer-issue-using-tiled2unity/1835

I can't tell if this is a misunderstanding on my part or an actual bug. Would appreciate any advice on how to implement this, as it would be a very helpful feature!

**Comment by Seanba** [comment]
I think it's likely there is a bug. Isometric has always been problematic.
My apologies I won't be able to look at it at least until this coming
weekend.

FTR, the layer index should match the same layer you want to interact with,
as you figured.

**Comment by so3arbelnox** [comment]
Thanks Sean and no problem about the wait. By the way, I am using a orthographic map. I have not tested isometric yet.

**Comment by Seanba** [comment]
Sorry it took so long but version 1.0.9.7 of Tiled2Unity contains a couple of fixes when using the Depth Buffer.

Also, this isn't fleshed out to a fully functioning demo yet, but if you [check out this project](https://github.com/Seanba/Tiled2Unity-DepthBuffer) there is a scene in place where you move a sprite around (in the editor) and have his "depth value" updated. You can see how that sprite is rendered in-front-of or behind different tiles as he changes location on the map.
