### ISSUE TITLE
Unknown problem with map importing

### ISSUE THREAD

**Issue by xuanquang1999** [Seanba/Tiled2Unity#80]
I had a problem with importing Tiled map to unity, which is shown in the image below.

![image](https://cloud.githubusercontent.com/assets/14069643/22402984/b305729c-e63c-11e6-9225-605963f42c84.png)

As you can see, everything is in pink. I figured out that only texture was successfully imported, everything else is in pink (which mean failed to import). I don't know what caused the problem. Is this a bug in your program, or it was my fault? 

I'm using Unity 5.4.4f1, Tiled 0.18.1, Tiled2Unity 1.0.9.4 (All of them are Window 32-bit version).

**Comment by Seanba** [comment]
Hi there. Can you send me your exported *.tiled2unity.xml file? It's found
in Assets/Tiled2Unity/Imported. Thanks.

**Comment by xuanquang1999** [comment]
Here's my exported file
[Forest 1.tiled2unity.xml.zip](https://github.com/Seanba/Tiled2Unity/files/738044/Forest.1.tiled2unity.xml.zip)

**Comment by Seanba** [comment]
FWIW, I was able to import your map without any problem. Can you check the Console window in Unity for any warnings or errors?

![image](https://cloud.githubusercontent.com/assets/6980630/22564283/95f144aa-e949-11e6-973d-6c4f944a3e71.png)

**Comment by xuanquang1999** [comment]
That's ... weird. What version of Unity you are using?

**Comment by Seanba** [comment]
I tested this with Unity 5.5.0f3. Are you getting any errors our warnings in your Console window?

**Comment by henrisokka** [comment]
I encountered this same bug. In shaTiledMap -shader it says "Can't find include file Tiled2Unity.cginc"

**Comment by Seanba** [comment]
Hi genriskokka, that is a different bug and appears to be a problem with the current distribution I just push last night. There is a fix incoming but in the meantime you can disable the line trying to include Tiled2Unity.cginc or go back to using Tiled2Unity 1.0.10.3 (which I just rolled back to on itch.io). Thanks for alerting me to the problem!

**Comment by Seanba** [comment]
henrisokka, the latest version of Tiled2Unity has the missing shader file. Thanks for letting me know.
