### ISSUE TITLE
Question about seams in isometric view

### ISSUE THREAD

**Issue by racingcow** [Seanba/Tiled2Unity#82]
Hello,

I get seams after importing to Unity 5.5 in an isometric game. It can be seen on the test map...

![image](https://cloud.githubusercontent.com/assets/1176637/22852218/1acb61a6-effd-11e6-94d0-90a15a369091.png)

I'm curious: Does the technique at http://www.firebelly.net/post/114529965784/tile-gaps-using-unity-5-and-tiled2unity work for isometric tiled maps as well?

**Comment by Seanba** [comment]
Hello racingcow, yes you'll want to something similar to that technique, especially for isometric maps as seams are especially bad for that type.

I talk about that a bit on my blog (see the part of visual seams): http://www.seanba.com/iso-hex-maps.html
