### ISSUE TITLE
Can't seem to get colliders to export

### ISSUE THREAD

**Issue by fregas** [Seanba/Tiled2Unity#83]
Thanks so much for this great tool!  One thing I can't figure out is how to export colliders.  I read an article and it sounds like I should be able to open the View Collider window, put the collider on my tile in Tiled, export to Unity using Tiled2Unity and then that part of my map should have a collider already on there w/ the appropriate shape.  However, I'm not seeing any colliders on my map objects in Unity.

**Comment by fregas** [comment]
Here's some screengrabs.  Maybe this functionality doesn't exist in Tiled2Unity anymore?  Or I'm looking in the wrong place.  Thanks.  

<img width="1439" alt="screen shot 2017-02-12 at 8 01 03 am" src="https://cloud.githubusercontent.com/assets/362617/22862717/8f7b8326-f0f9-11e6-9c10-32666f084cac.png">

<img width="1136" alt="screen shot 2017-02-12 at 8 03 05 am" src="https://cloud.githubusercontent.com/assets/362617/22862729/ce2b277a-f0f9-11e6-99e3-a25b8bd66280.png">


<img width="1439" alt="screen shot 2017-02-12 at 8 01 48 am" src="https://cloud.githubusercontent.com/assets/362617/22862720/97ca93a0-f0f9-11e6-8c7b-820e884901e3.png">
<img width="1438" alt="screen shot 2017-02-12 at 8 01 57 am" src="https://cloud.githubusercontent.com/assets/362617/22862721/9ebaac36-f0f9-11e6-9e78-7214baa4a173.png">

**Comment by Seanba** [comment]
Helllo fregas, have you tried dragging that world prefab into your scene to instantiate a instance? The colliders should be in place (the asset folder doesn't show the full hierarchy of a prefab).

**Comment by fregas** [comment]
I did.  Here's what I see:

<img width="1438" alt="screen shot 2017-02-12 at 6 40 35 pm" src="https://cloud.githubusercontent.com/assets/362617/22867714/ce49cbd6-f152-11e6-93ab-60b2177637e2.png">

<img width="1430" alt="screen shot 2017-02-12 at 6 40 52 pm" src="https://cloud.githubusercontent.com/assets/362617/22867715/d0b4eb26-f152-11e6-8486-25454a6450bc.png">

**Comment by Seanba** [comment]
It looks like you're making heavy use of animation. In that case, make sure the tile that represents the animation (i.e. the tile you place in your map) has the colliders you need on it.

If that doesn't make sense or doesn't fix your map then send it to me (TMX + TSX and texture files) and I'll take a look.

**Comment by fregas** [comment]
It appears to.  How do you want me to send you the files?

**Comment by Seanba** [comment]
Hi again. You can find my email on my blog: www.seanba.com

**Comment by fregas** [comment]
I am using animation. I sent you the files.

**Comment by Seanba** [comment]
I'm closing this since it was resolved via email. For those wondering, the colliders are collected into a separate GameObject in the layer hierarchy and can be hard to see when you have a lot of animations.
