### ISSUE TITLE
renderer.sharedMaterial.mainTexture is always null during import

### ISSUE THREAD

**Issue by rwols** [Seanba/Tiled2Unity#84]
I have a custom importer where I want to replace the material of some MeshRenderers. The way I do this is I create the new material, then set the main texture of my new material as the texture of the old material attached to the MeshRenderer, then save it, then assign the new material to the MeshRenderer.

However, it seems that the following code always fails at getting the texture of the current material, as `texture` is always null

```c#
	private bool ReplaceMaterialWithDecalMaterial(MeshRenderer renderer)
	{
		var material = renderer.sharedMaterial;
		if (!material)
		{
			Debug.LogWarningFormat("Renderer \"{0}\" has no material", renderer.name);
			return false;
		}
		var texture = material.GetTexture("_MainTex");
		if (!texture)
		{
			Debug.LogWarningFormat("Could not fetch texture from renderer \"{0}\"", renderer.name);
			return false;
		}
		material = new Material(Shader.Find("Tiled2Unity/DefaultWithDecals"));
		material.name = texture.name;
		material.SetTexture("_MainTex", texture);
		var path = string.Format("Assets/Materials/{0}.mat", material.name);
		material = Tiled2Unity.ImportUtils.CreateOrReplaceAsset<Material>(material, path);
		if (!material)
		{
			Debug.LogWarningFormat("Could not create or replace new decal material named \"{0}\"", material.name);
			return false;
		}
		renderer.sharedMaterial = material;
		return true;
	}
```

This all happens inside `ICustomImporter.HandleCustomProperties`

Does anyone know of a workaround for this?

**Comment by Seanba** [comment]
Rwols, I just tried something similar where I'd get a `MeshRenderer` component and get the main texture from the shared material and it worked okay for me. Perhaps if send me the code for your full custom importer I can check that out?

**Comment by rwols** [comment]
Sure! [Here's the contents](https://gist.github.com/rwols/04df26ef4a1f5eeb95d9835ba9002b31)

**Comment by Seanba** [comment]
That looks like it should work. What is this DefaultWithDecals shader though? Does it have a _MainTex texture property?

**Comment by rwols** [comment]
That's a very simple modified shader (modified from Tiled2Unity/Default) that uses a stencil buffer in some places; it's located in Assets/Shaders/DefaultWithDecals.shader (the default Tiled2Unity shader is located in Assets/Tiled2Unity/Shaders/shaDefault.shader)

**Comment by rwols** [comment]
But the code bails already at the line

```
var texture = material.GetTexture("_MainTex");
```

For instance I have a layer (GameObject in unity) called "Ground", that GO has two children named "City" and "Collision", "City" houses the MeshRenderer and "Collision" houses the collision info. Now that I think about it, I probably could find the texture via the name of the child GameObject (called "City", the same name as the texture which is called "City.png"), but that would be kind of a hack

**Comment by Seanba** [comment]
If you modified the default Tiled2Unity shader then you may have a [PerRendererData] attribute on the _MainTex property. Try deleting that attribute in your DefaultWithDecals.shader and see if that helps.

**Comment by rwols** [comment]
The shader does have a [PerRendererData] attribute on _MainTex. I removed that but it doesn't have any effect. 😞

**Comment by rwols** [comment]
So, I notice that the Tiled2Unity default shader also has `[PerRendererData]`, perhaps it's impossible to get at the texture if such an attribute is present? I'm still not sure what that does.

**Comment by Seanba** [comment]
Yeah, remove that one too just to see if that works. PerRendererData puts the property into a MaterialProperty instance which may be stopping you from accessing it.

**Comment by rwols** [comment]
OK well, I removed that attribute and it didn't have any effect. Next I tried reimporting all assets, but now I get the following errors:
```
Error importing texture 'Assets/Tiled2Unity/Textures/City.png'. Could not find material. Try re-importing Tiled2Unity/Imported/[MapName].tiled2unity.xml file
```
I'm starting to believe that there's a deeper problem somewhere 🤔

**Comment by Seanba** [comment]
Try re-importing just one *.tiled2unity.xml file. If that isn't getting you any closer to a working solution then put your project into a Unity Package and have me take a look.

**Comment by rwols** [comment]
I'll try that for tomorrow!

**Comment by rwols** [comment]
OK so, I solved the problem by just hacking it in by taking `renderer.gameObject.name`, that name corresponds to the texture filename (without the .png extension), so I used that to solve the problem.

Then there were these strange Texture2D import errors coming from Tiled2Unity, and I hacked that away by just commenting out the material importing logic. All the materials are already present and we're not going to need new materials, the game is almost finished

I have a bunch of changes made to Tiled2Unity so I was hesitant to update it to the latest HEAD. I also made a bunch of changes in how the meshes were realized in the Tiled2Unity exporter (see [this PR](https://github.com/Seanba/Tiled2Unity/pull/55)), so I'm scared to rebase.

Anyway, the problem is solved. I notice you used a new third party library called LibTess? Is that supposed to generate mesh triangles from the collision triangles from ClipperLib? How would that work with the UVs?

**Comment by Seanba** [comment]
Okay. I understand why you wouldn't want to update but glad you got things fixed up.

To your last question: LibTess is only used for convex collision geometry. It triangulates the (potentially complex / concave) results from Clipper and then those triangles are merged into convex polygons. (So, nothing to do with UVs)
