### ISSUE TITLE
Strange issue when importing some .tmx files #74 2

### ISSUE THREAD

**Issue by ManuelNerdOD** [Seanba/Tiled2Unity#85]
Hey im having the exact same problem as the person who made the post with the same name as this one had but that page never got an answer to that problem. And ive been using tiled2unity alot lately but every so often on map wont import and it just creats the random gameObject __tiled2unity_importer please help

**Comment by Seanba** [comment]
Hi there. Are you seeing any errors or warnings in the Unity console window?

**Comment by ManuelNerdOD** [comment]
Hi thanks for helping, but no, no errors or warnings


2017-02-21 23:15 GMT+00:00 Seanba <notifications@github.com>:

**Comment by Seanba** [comment]
Can you send me your exported *.tiled2unity.xml file? I'll try to import it myself and see what's going on.

**Comment by ManuelNerdOD** [comment]
Sure Thing
Here it goes.

2017-02-21 23:39 GMT+00:00 Seanba <notifications@github.com>:

**Comment by Seanba** [comment]
I didn't receive it. I think Github notifications removes attached files. Look on www.seanba.com for my email address and send it to me directly there. Thanks.

**Comment by ManuelNerdOD** [comment]
I just sent it, can you confirm if you received it and if not send me your
e-mail for me to try again


2017-02-21 23:44 GMT+00:00 Seanba <notifications@github.com>:

**Comment by Seanba** [comment]
Turns out Manuel found a bug when the same texture is used across different maps but the name of the texture is different case. (i.e. one TMX file uses `MyTexture.png` and the other uses `mytexture.png`)

I will roll a fix into the next version of Tiled2Unity. In the meantime your maps will need to be consistent in how they reference texture names.

**Comment by ManuelNerdOD** [comment]
So your saying that the name of the tiles should be the same in all the the
maps. Like the name that tiled askes when you import a tile sheet onto
Tiled?

2017-02-22 2:11 GMT+00:00 Seanba <notifications@github.com>:

**Comment by Seanba** [comment]
No, the name can be different but the source has to be the same case. I'm guessing (mind you, just a guess) that you had a file named col.png that you used as a tileset for some of your maps and then you "renamed" it to Col.png at some point and used it as a tileset for another map.

![image](https://cloud.githubusercontent.com/assets/6980630/23194552/63e5ee0e-f874-11e6-8b2f-b9e88714d10b.png)

**Comment by ManuelNerdOD** [comment]
I've Just put all 3 maps with the same name (in the first two it was writen
"col" and the broken one said "Col") but its still not working? What was
that idea of importing a custome package?


2017-02-22 2:20 GMT+00:00 Manuel Santos Afonso <
manuel.santos.afonso@gmail.com>:

**Comment by Seanba** [comment]
I sent you a custom Unity Package that should contain the fix I'm going to put into the next version of Tiled2Unity. The importer will no longer care about case-sensitivity. Did you try importing that package into your Unity project?

**Comment by ManuelNerdOD** [comment]
Ok so tried my best to correct that and make it so all the maps are
consistent and then i deleted the ones on the project to replace with the
new ones but no none of them are beeing importent. But now its showing an
error, which is: "NullReferenceException: Object reference not set to an
instance of an object
Tiled2Unity.ImportTiled2Unity.ImportAllMaterials
(Tiled2Unity.ImportBehaviour importComponent) (at
Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Material.cs:87)
Tiled2Unity.ImportTiled2Unity.TextureImported (System.String texturePath)
(at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Texture.cs:30)
Tiled2Unity.TiledAssetPostProcessor.OnPostprocessAllAssets (System.String[]
importedAssets, System.String[] deletedAssets, System.String[] movedAssets,
System.String[] movedFromPath) (at
Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs:87)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags
invokeAttr, System.Reflection.Binder binder, System.Object[] parameters,
System.Globalization.CultureInfo culture) (at
/Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the
target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags
invokeAttr, System.Reflection.Binder binder, System.Object[] parameters,
System.Globalization.CultureInfo culture) (at
/Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[]
parameters) (at
/Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets
(System.String[] importedAssets, System.String[] addedAssets,
System.String[] deletedAssets, System.String[] movedAssets, System.String[]
movedFromPathAssets) (at"

2017-02-22 2:29 GMT+00:00 Seanba <notifications@github.com>:

**Comment by Seanba** [comment]
Can you send me your project again then? (BTW, right-click on your Assets folder in your Unity and select `"Export Package..."` and send me that. It's much better than zipping up your whole Unity folder).

**Comment by ManuelNerdOD** [comment]
Do you mind if I send it tomorrow? Its kinda late where I live.

**Comment by Seanba** [comment]
Yeah, that's cool. Have a good night. :)

(BTW, I'm super-confident this will be resolved)

**Comment by ManuelNerdOD** [comment]
Thanks this is our first game and were doing our best to make into
something were proud of

**Comment by ManuelNerdOD** [comment]
Hello  Sean thanks for all the help but for some reason everything is
working now. Ive been able to import all maps. Thanks ill be in contact if
i get this issue again


2017-02-22 3:00 GMT+00:00 Manuel Santos Afonso <
manuel.santos.afonso@gmail.com>:

> Thanks this is our first game and were doing our best to make into
> something were proud of
>

**Comment by Seanba** [comment]
Glad to hear. I suspect what might have happened is that you had a rogue `__tiled2unity_importer` game object still in your scene from previous failed imports. Shutting down for the night may have put you back into a clean state. In any case, I'll roll the proper fix into the next Tiled2Unity release soon. Thanks for reporting the bug.

**Comment by Seanba** [comment]
Tiled2Unity version 1.0.10.1 was just released and will handle issues like this in the future.
