### ISSUE TITLE
Depth buffer issues in 1.0.9.5

### ISSUE THREAD

**Issue by so3arbelnox** [Seanba/Tiled2Unity#86]
Hello,

I am still having depth buffer issues after the fixes in 1.0.9.5. I am using an orthographic map and as far as I can tell isometric maps are working after testing your sample project.

The issue seems to be related to the SpriteDepthInMap script and the "Placed on Layer Index" property. If I set this equal to the layer I will interact with, it does not work. However, if I set the value equal to the current y-tile the player is occupying it seems to mostly work.

Do you have any ideas on what may be causing this?

**Comment by Seanba** [comment]
I'd have to take a look at your project to see where the problem is. Can you export your project as a Unity Project and send it to me? (Right click on your Assets folder in Unity and select "Export Package...")

**Comment by so3arbelnox** [comment]
[Thanks for the quick reply! The layer he is interacting with is the upper layer (the top full sections of the pillars for example). Where can I upload the project for you to see? Github is complaining when I try attaching a zip or the package file. "We don't support that file type".

**Comment by so3arbelnox** [comment]
I see in another issue it removes files automatically so I sent to your email.

**Comment by Seanba** [comment]
Tiled2Unity version 10.0.10.1 has depth buffer fixes in it. One thing to keep in mind is that the order of your layers is very important (i.e. They should stack on top of each other as each layer as you go up increases in depth)
