### ISSUE TITLE
Compiling error in Unity Project(circleobject.cs)

### ISSUE THREAD

**Issue by peterkr10** [Seanba/Tiled2Unity#87]
The script has:
Using UnityEditor;

change to:
Using UnityEngine;

and it will work.

**Comment by Seanba** [comment]
Thanks. I'll fix this in the next release of Tiled2Unity.

**Comment by z3ntu** [comment]
Any ETA of that release? It's breaking Unity Cloud build for me.

**Comment by Seanba** [comment]
It's coming with a bunch of other fixes so may be a day or two still. In the meantime comment out the offending line.

**Comment by Seanba** [comment]
Tiled2Unity version 1.0.10.1 was just released with this fix.
