### ISSUE TITLE
Handle different tiles with same filename

### ISSUE THREAD

**Issue by z3ntu** [Seanba/Tiled2Unity#88]
Currently we have multiple .tmx files for different levels that are made with different tilesets in different folders. When we then import the two levels (tiles are called eg 1.png) into Unity, the tiles will be the same in both prefabs. If you need more information / our levels just tell me. Thanks

**Comment by Seanba** [comment]
With Tiled2Unity version 1.0.11.0 you can add custom properties to the tileset to apply prefix and/or postfix decoration to each texture in the tileset, thereby making them unique upon export.

You can read about it here: http://tiled2unity.readthedocs.io/en/latest/prepostfix/
