### ISSUE TITLE
Error Creating Material

### ISSUE THREAD

**Issue by brock555** [Seanba/Tiled2Unity#90]
Upgraded to 10.0.10.1 tonight and started getting this error when importing:

`Error creating material with shader 'Tiled2Unity/Default'. 
UnityEngine.Debug:LogError(Object)
Tiled2Unity.ImportBehaviour:RecordError(String, Object[]) (at Assets/Tiled2Unity/Scripts/Runtime/ImportBehaviour.cs:159)
Tiled2Unity.ImportTiled2Unity:CreateMaterialFromXml(XElement, ImportBehaviour) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Xml.cs:120)
Tiled2Unity.ImportTiled2Unity:ImportAllMaterials(ImportBehaviour) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Material.cs:102)
Tiled2Unity.ImportTiled2Unity:TextureImported(String) (at Assets/Tiled2Unity/Scripts/Editor/ImportTiled2Unity.Texture.cs:30)
Tiled2Unity.TiledAssetPostProcessor:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/Tiled2Unity/Scripts/Editor/TiledAssetPostProcessor.cs:87)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])`

I'm running Unity 5.6 f1 on Mac

**Comment by Seanba** [comment]
Hi Brock. This looks like you don't have the Tiled2Unity shaders (or perhaps they've been renamed?). Do you have the unmodified Assets/Tiled2Unity/Shaders/shaTiledMap.shader file in your Unity project?

**Comment by brock555** [comment]
Are the shaders (shaColorKey, shaDefault, shaDepth, shaDepthColorKey, shaDiffuseDepth) no longer needed? When I browse the source of 10.0.10.1 the only shader I see is shaTiledMap.

**Comment by brock555** [comment]
I see whats going on, the GitHub repo doesn't contain those shaders. Could you update the repo to match the unity package? It might avoid confusion with other people in the future.

**Comment by Seanba** [comment]
Hi brock555 the repo has been updated. Sorry it took so long. I've been busy with work. :)
