### ISSUE TITLE
HandleCustomProperties

### ISSUE THREAD

**Issue by brock555** [Seanba/Tiled2Unity#93]
What do you think about moving HandleCustomProperties to the end of **AddGameObjectsTo**? This way all the rotation and scaling is already taken care of. I ask because because I was having issues with correctly positioning some custom objects that have been scaled and rotated. If i move that method call to the end everything is positioned perfectly.

**Comment by Seanba** [comment]
Hello brock555. Yes, this is a good idea and will be in the next version of Tiled2Unity.

(Forgive the lateness of my reply.)

**Comment by Seanba** [comment]
This was fixed with version 1.0.11.0 of Tiled2Unity, just recently published. Thanks again for the suggestion.
