### ISSUE TITLE
Prefabs are not showing up

### ISSUE THREAD

**Issue by lancearmada** [Seanba/Tiled2Unity#94]
I am attempting to import files from tiled to unity using this program, and i have an issue where no prefabs are actually being created. I imported the tiled2unity package, and i located the tiled2unity.export file. I select my tmx file using the dropdown at the top left of the window, and then preview my map, everything seems fine, and so i hit the big ass export button. When i go into unity there are no files inside of the prefab folder except for the read me, although there is a file inside of the imported folder. I'm not sure why this could be. I am using Unity 5.5.1f1 Personal 64 bit and i am using the 64 bit version of tiled2unity for windows. I have windows 10, and im creating a game for the pc platform.
Help or information would be appreciated.

**Comment by Seanba** [comment]
Everything should be good to go once you have an exported *.tiled2unity.xml file in your Assets/Tiled2Unity/Imported folder. Are there any errors or warnings in Unity's console window? (Press CTRL+SHIFT+C in Unity to see it.)

**Comment by dbrereton1995** [comment]
I had the exact same problem. However, another instance of this issue was recorded and closed  in 2016.

On June 29th 2016, Topwise said:
> If you have this problem, BUT you get no errors and no prefab, you may be doing what I did.
>After you hit the B.A. Export button, DO NOT EXIT the Tiled2Unity app. Just click on Unity.
(I clicked on the console window just to make sure)
>When I realized that I was clicking export, thinking it exported already to the project. I would then close the application. Then i would switch to unity. It does not move your items to unity unless it is still open and you click on unity after exporting.

Assuming you've taken Seanba's advice into consideration then this should provide a fix.

Also cheers for the tool @Seanba it's ridiculously useful!

**Comment by Seanba** [comment]
It's been a couple of months without further information so I'm going to close this out. If your problem has not been resolved you can re-open with some more information. Thanks.

**Comment by cyrus027** [comment]
I'm facing the same problem. No errors and warnings in the console I even downloaded the latest tiled2unity but still not working. I see the maps that i created in the imported files but the prefabs is still none.

**Comment by Seanba** [comment]
Hi Cyrus. If you send me your wrap your Unity project up into a Unity Package and send it to me I'll take a look. You can find my email on my blog: www.seanba.com

**Comment by pkenau** [comment]
I'm having the same problem, but no errors. But my tile2unity version it is the mac.

**Comment by Hijumi** [comment]
I have the problem that only the collider lodes in to unity, i can se the map in preview but in game its No map and only glowing colliders

**Comment by Seanba** [comment]
Hi there, @Hijumi. I recommend using SuperTiled2Unity as this is now old software. Thanks.

**Comment by Hijumi** [comment]
Thank you, i will do so
