### ISSUE TITLE
Sprites added as collection of images and put on an Object Layer lack some features

### ISSUE THREAD

**Issue by Kalmend** [Seanba/Tiled2Unity#95]
When I import a sprite as a collection of images to Tiled and add multiple colliders to the single sprite, they dont get categorized by the Type property. It works fine for tiles on Tile Layers. Tiled2Unity Preview also shows all of the tiles as gray, while in Tiled they get colored according to their object type. 

As a workaround I tried using the unity:isTrigger on one of the colliders under my sprite, but this too doesn't work.

**Comment by Seanba** [comment]
Hi Kalmend, yes, all collision layers on a Tile Object have inherited their setting from the Object Layer they are a part of. This was not my intention. I should have a fix for this in the coming day or two.

**Comment by Seanba** [comment]
Kalmend, this was fixed with version 1.0.11.0 of Tiled2Unity. Thanks for the bug report.
