### ISSUE TITLE
Textures with a same name cause error

### ISSUE THREAD

**Issue by AyoCrazy** [Seanba/Tiled2Unity#96]
I import two folder into Tiled Map Editor, which both has a texture with the same name。It worked 
well in the editor.But when I tyr to import tmx to Unity, only one texture with the name was imported. And all the tile which need the missing texture used the wrong texture instead.It did't work well in unity.

**Comment by Seanba** [comment]
Thanks for the bug report. I'm not sure the best way to handle this but I'll try to come up with something.

**Comment by Seanba** [comment]
With Tiled2Unity version 1.0.11.0 you can add custom properties to the tileset to apply prefix and/or postfix decoration to each texture in the tileset, thereby making them unique upon export.

You can read about it here: http://tiled2unity.readthedocs.io/en/latest/prepostfix/
