### ISSUE TITLE
Exception when setting transparent color

### ISSUE THREAD

**Issue by Kalmend** [Seanba/Tiled2Unity#97]
TmxImage::FromXml call to tmxImage.ImageBitmap.SetPixel(x, y, transColor); throws an exception:
"This method is not supported for bitmaps with ColorTypes of Index8."

**Comment by Seanba** [comment]
Can you send me the texture or bitmap you're using in this example? Thanks.

**Comment by Seanba** [comment]
I think I know what's going on. You're using a palletized bitmap format an I'm not handling that format at the moment. I'll put out a fix later today.

**Comment by Seanba** [comment]
This was fixed with Tiled2Unity version 1.0.11.1. Thanks again for notifying me of the issue.
