### ISSUE TITLE
Sprites not showing up in Unity

### ISSUE THREAD

**Issue by FPorcher** [Seanba/Tiled2Unity#98]
Hey Seanba,

I'm currently creating a Standalone for Windows in Unity and just made my first map in Tiled. I'm using the 1.0.11.1 version of Tiled2Unity for Windows.
I loaded a sprite sheet in Tiled as my only tileset and just made the entire map with one layer from one sprite.
Next, I opened the File in Tiled2Unity, chose the Tiled2Unity.export.txt file and checked that the preview was correct. Then clicked the fat ass export button and the Prefab was loaded to Unity.
The problem is that in the preview and also when I drag the prebaf to my world I can only see a massive pink sprite! In the Materials and Meshes folder the same thing happened. 
Can you help me solving this issue?

![problem](https://cloud.githubusercontent.com/assets/24586748/25456101/3d5ccd62-2ad2-11e7-8637-412b91854fb1.png)

Thanks!

**Comment by Seanba** [comment]
When you export, are there any errors or warnings in the Unity Console window? (Press CTRL+SHIFT+C to bring up that window in Unity)

**Comment by FPorcher** [comment]
Seanba,

I updated with a foto to better explain what is my issue.

**Comment by Seanba** [comment]
Hi again, FPorcher.  Can you check for errors in the Unity Console window? When something does go wrong with Tiled2Unity there is generally an error printed out that tells you what went wrong with the import process.

**Comment by FPorcher** [comment]
Seanba,

There are no errors at the Unity Console Windows, but going deeper I found errors inside the Shaders folder. I don't know if it's related, but I'm sending it.

![image](https://cloud.githubusercontent.com/assets/24586748/25456485/491a9c50-2ad3-11e7-8903-682224df3b10.png)

**Comment by Seanba** [comment]
I meant to add you should re-export with the Console window open. But yes, that shader error is certainly the cause of your problem. Can you copy and past the full error? BTW, which version of Unity are you using?

**Comment by FPorcher** [comment]
Oh ok. There are 0 warnings and 0 errors. I'm currently using 5.3.2.f1 Personal
The shader error is: 

undeclared identifier 'unity_ObjectToWorld'
Compiling Vertex program with DUMMY
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_TEXTURE_ALPHASPLIT_ALLOWED

**Comment by Seanba** [comment]
Hmmm ... it looks like Unity auto-upgraded a file on you maybe? Can you send me your copy of Tiled2Unity.cginc?

**Comment by FPorcher** [comment]
Yeah, sure.
I can't upload directly here so I sent to your email.

**Comment by Seanba** [comment]
This seems to be a problem with how Tiled2Unity is handling backwards compatibility with versions of Unity before 5.4. I'll get a fix out soon.

**Comment by FPorcher** [comment]
Thanks for the quick answer!!
Keep up the good work.

**Comment by FPorcher** [comment]
I just tested it and it's working perfectly!
Thanks again.

**Comment by Seanba** [comment]
The fix was made public with version 1.0.11.2 of Tiled2Unity. Thanks for the bug report.
